'use client';

import { Check,ExternalLink,LockKeyhole,RefreshCw,Signal,Trash2,Wifi,WifiOff,X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { type WifiNetwork, useWifiConnectivity } from '../lib/use-wifi-connectivity';
import { useI18n } from '../lib/i18n';

export default function ConnectivitySettings(){
  const wifi=useWifiConnectivity();const{isVietnamese}=useI18n();
  const[selectedSsid,setSelectedSsid]=useState<string|null>(null);const[password,setPassword]=useState('');
  const selected=useMemo(()=>wifi.networks.find((item)=>item.ssid===selectedSsid)??null,[selectedSsid,wifi.networks]);
  const signalLabel=(level:number)=>isVietnamese?(level>=4?'Rất tốt':level===3?'Tốt':level===2?'Trung bình':level===1?'Yếu':'Rất yếu'):(level>=4?'Excellent':level===3?'Good':level===2?'Fair':level===1?'Weak':'Very weak');

  async function chooseNetwork(network:WifiNetwork){if(wifi.connectedSsid===network.ssid)return;if(network.saved){const connected=await wifi.reconnect(network.ssid);if(connected)return;}if(!network.secure){await wifi.connect(network.ssid);setSelectedSsid(null);setPassword('');return;}setSelectedSsid(network.ssid);setPassword('');}
  async function connectSelected(){if(!selected)return;const connected=await wifi.connect(selected.ssid,password || undefined);if(!connected)return;setPassword('');setSelectedSsid(null);}

  return <section className="connectivitySettings" aria-labelledby="wifi-settings-title" data-testid="wifi-settings">
    <div className="connectivityHeader"><span><Wifi/><span><strong id="wifi-settings-title">{isVietnamese?'Wi‑Fi & kết nối':'Wi-Fi & connectivity'}</strong><small>{isVietnamese?'Thiết lập mạng chỉ khả dụng khi xe đang đỗ.':'Network setup is available while parked.'}</small></span></span><b>{wifi.mode==='native'?(wifi.connectedSsid??(wifi.enabled?(isVietnamese?'Chưa kết nối':'Not connected'):(isVietnamese?'Wi‑Fi tắt':'Wi-Fi off'))):(wifi.online?(isVietnamese?'Máy chủ online':'Host online'):(isVietnamese?'Máy chủ offline':'Host offline'))}</b></div>
    {wifi.mode==='host-managed'?<div className="hostManagedWifi"><span className={`wifiStateIcon ${wifi.online?'isOnline':''}`}>{wifi.online?<Wifi/>:<WifiOff/>}</span><span><strong>{isVietnamese?'Do thiết bị chủ quản lý':'Managed by host device'}</strong><small>{isVietnamese?'Bản web không thể bật/tắt radio Wi‑Fi, quét SSID hoặc lưu thông tin mạng. Phần cứng xe cần cung cấp KINGMAST native Wi‑Fi bridge.':'The web preview cannot switch the Wi-Fi radio, scan SSIDs, or store network credentials. Vehicle hardware should expose the KINGMAST native Wi-Fi bridge for those controls.'}</small></span><button type="button" onClick={()=>void wifi.refresh()}><RefreshCw/> {isVietnamese?'Làm mới':'Refresh'}</button></div>:<>
      <div className="wifiMasterRow"><span className={`wifiStateIcon ${wifi.enabled?'isOnline':''}`}>{wifi.enabled?<Wifi/>:<WifiOff/>}</span><span><strong>Wi‑Fi</strong><small>{wifi.enabled?(wifi.connectedSsid?(isVietnamese?`Đã kết nối ${wifi.connectedSsid}`:`Connected to ${wifi.connectedSsid}`):(isVietnamese?'Bật · chọn mạng bên dưới':'On · choose a network below')):(isVietnamese?'Tắt · bản đồ online và connected-road sẽ tạm dừng':'Off · online maps and connected-road services will pause')}</small></span><button type="button" role="switch" aria-label="Wi-Fi" aria-checked={Boolean(wifi.enabled)} className={`appleSwitch ${wifi.enabled?'isOn':''}`} disabled={wifi.busy} onClick={()=>void wifi.setEnabled(!wifi.enabled)}><span/></button></div>
      {wifi.captivePortal?<div className="wifiPortalCard" role="status"><ExternalLink/><span><strong>{isVietnamese?'Cần đăng nhập mạng':'Network sign-in required'}</strong><small>{isVietnamese?'Wi‑Fi đã kết nối nhưng dịch vụ online tạm dừng đến khi thiết bị chủ hoàn tất đăng nhập mạng.':'Wi-Fi is connected, but online services are paused until the host completes network sign-in.'}</small></span><button type="button" onClick={()=>void wifi.openCaptivePortal()}>{isVietnamese?'Đăng nhập':'Sign in'}</button></div>:null}
      {wifi.enabled?<div className="wifiNetworks"><div className="wifiNetworksHead"><span><Signal/> {isVietnamese?'Mạng khả dụng':'Available networks'}</span><button type="button" disabled={wifi.busy} onClick={()=>void wifi.scan()}><RefreshCw className={wifi.busy?'isSpinning':''}/> {wifi.busy?(isVietnamese?'Đang quét…':'Scanning…'):(isVietnamese?'Quét':'Scan')}</button></div>{wifi.networks.length?wifi.networks.map((network)=>{const connected=wifi.connectedSsid===network.ssid;return <div className={`wifiNetworkRow ${connected?'isConnected':''}`} key={network.ssid}><button type="button" className="wifiNetworkMain" disabled={wifi.busy||connected} onClick={()=>void chooseNetwork(network)}><span>{network.secure?<LockKeyhole/>:<Wifi/>}</span><span><strong>{network.ssid}</strong><small>{signalLabel(network.signal)}{network.saved?(isVietnamese?' · Mạng đã lưu':' · Known network'):''}</small></span><b>{connected?<><Check/> {isVietnamese?'Đã kết nối':'Connected'}</>:network.saved?(isVietnamese?'Kết nối lại':'Reconnect'):network.secure?(isVietnamese?'Bảo mật':'Secure'):(isVietnamese?'Mở':'Open')}</b></button><div className="wifiNetworkActions">{connected?<button type="button" className="wifiDisconnect" disabled={wifi.busy} onClick={()=>void wifi.disconnect()}><X/> {isVietnamese?'Ngắt kết nối':'Disconnect'}</button>:null}{network.saved?<button type="button" className="wifiForget" disabled={wifi.busy} onClick={()=>void wifi.forget(network.ssid)}><Trash2/> {isVietnamese?'Quên mạng':'Forget'}</button>:null}</div></div>;}):<div className="wifiEmpty">{isVietnamese?'Chưa có mạng nào được quét. Chọn Quét khi xe đang đỗ.':'No scanned networks yet. Select Scan while parked.'}</div>}</div>:null}
      {selected?<div className="wifiCredentialCard" role="group" aria-label={isVietnamese?`Kết nối ${selected.ssid}`:`Connect to ${selected.ssid}`}><span><LockKeyhole/><span><strong>{selected.ssid}</strong><small>{selected.saved?(isVietnamese?'Thông tin đã lưu không kết nối lại được. Nhập mật khẩu hiện tại để khôi phục mạng.':'Saved credentials could not reconnect. Enter the current password to recover this network.'):(isVietnamese?'Mật khẩu chỉ gửi tới native vehicle network service và không lưu trong web UI.':'Password is sent only to the native vehicle network service and is not stored by the web UI.')}</small></span></span><label><span>{isVietnamese?'Mật khẩu mạng':'Network password'}</span><input autoComplete="off" type="password" value={password} onChange={(event)=>setPassword(event.target.value)} placeholder={isVietnamese?'Nhập mật khẩu':'Enter password'}/></label><div><button type="button" onClick={()=>{setSelectedSsid(null);setPassword('');}}>{isVietnamese?'Hủy':'Cancel'}</button><button type="button" className="wifiConnectPrimary" disabled={wifi.busy||password.length===0} onClick={()=>void connectSelected()}>{wifi.busy?(isVietnamese?'Đang kết nối…':'Connecting…'):(isVietnamese?'Kết nối':'Connect')}</button></div></div>:null}
    </>}
    {wifi.error?<div className="wifiError" role="status"><WifiOff/><span><strong>{isVietnamese?'Kết nối cần kiểm tra':'Connectivity needs attention'}</strong><small>{wifi.error}</small></span><button type="button" disabled={wifi.busy} onClick={()=>void wifi.refresh()}><RefreshCw/> {isVietnamese?'Thử lại':'Retry'}</button></div>:null}
  </section>;
}
