'use client';

import { AlertTriangle,CarFront,Check,ChevronRight,LocateFixed,MapPinned,ShieldCheck,Wifi,WifiOff } from 'lucide-react';
import { useEffect,useMemo,useState } from 'react';
import { useHmiPreferences } from '../lib/use-hmi-preferences';
import { useDriverProfile } from '../lib/use-driver-profile';
import { useI18n } from '../lib/i18n';

export const FIRST_RUN_STORAGE_KEY='kingmast:v006:first-run-complete';
type LocationState='checking'|'prompt'|'requesting'|'granted'|'denied'|'unavailable';
type Step='welcome'|'location'|'connectivity'|'ready';
const STEPS:Step[]=['welcome','location','connectivity','ready'];

function locationCopy(state:LocationState,isVietnamese:boolean){
  if(state==='granted')return{title:isVietnamese?'Vị trí đã sẵn sàng':'Location ready',message:isVietnamese?'Dẫn đường có thể dùng vị trí của thiết bị khi bạn chọn GPS thiết bị.':'Navigation can use this device location when you choose device GPS.'};
  if(state==='denied')return{title:isVietnamese?'Chưa cho phép vị trí':'Location not allowed',message:isVietnamese?'Bạn vẫn có thể tiếp tục. Dẫn đường sẽ dùng chế độ mô phỏng hoặc GNSS của xe cho tới khi quyền thay đổi.':'You can continue. Navigation will stay in simulator or vehicle-GNSS mode until permission changes.'};
  if(state==='unavailable')return{title:isVietnamese?'Không có vị trí từ thiết bị':'Location unavailable',message:isVietnamese?'Thiết bị chủ không cung cấp geolocation qua trình duyệt. GNSS của xe vẫn có thể cung cấp vị trí.':'This host does not expose browser geolocation. Vehicle GNSS can still provide position.'};
  if(state==='requesting')return{title:isVietnamese?'Đang yêu cầu quyền vị trí…':'Requesting location…',message:isVietnamese?'Hãy dùng hộp thoại quyền của hệ thống để chọn có cho KINGMAST truy cập vị trí thiết bị hay không.':'Use the system permission prompt to choose whether KINGMAST may access device location.'};
  return{title:isVietnamese?'Vị trí chỉ dùng theo ngữ cảnh':'Location is contextual',message:isVietnamese?'KINGMAST chỉ yêu cầu vị trí cho dẫn đường và cảnh báo theo tuyến. Luồng thiết lập ban đầu không lưu tọa độ.':'KINGMAST requests location only for navigation and route-aware warnings. The first-run flow does not store coordinates.'};
}

export default function FirstRunExperience({onComplete}:{onComplete:()=>void}){
  const[index,setIndex]=useState(0);const[locationState,setLocationState]=useState<LocationState>('checking');const[online,setOnline]=useState(true);const{preferences,updatePreferences}=useHmiPreferences();const[advisories,setAdvisories]=useState(preferences.advisoryAlerts);const{profile,updateProfile}=useDriverProfile();const{isVietnamese}=useI18n();
  const tx=(en:string,vi:string)=>isVietnamese?vi:en;const step=STEPS[index];const location=useMemo(()=>locationCopy(locationState,isVietnamese),[isVietnamese,locationState]);

  useEffect(()=>{setAdvisories(preferences.advisoryAlerts);},[preferences.advisoryAlerts]);
  useEffect(()=>{
    if(typeof navigator==='undefined'){setLocationState('unavailable');return;}
    setOnline(navigator.onLine);
    const onOnline=()=>setOnline(true);const onOffline=()=>setOnline(false);window.addEventListener('online',onOnline);window.addEventListener('offline',onOffline);
    if(!navigator.geolocation){setLocationState('unavailable');return()=>{window.removeEventListener('online',onOnline);window.removeEventListener('offline',onOffline);};}
    if(!navigator.permissions){setLocationState('prompt');return()=>{window.removeEventListener('online',onOnline);window.removeEventListener('offline',onOffline);};}
    let status:PermissionStatus|null=null;let disposed=false;
    void navigator.permissions.query({name:'geolocation' as PermissionName}).then((next)=>{if(disposed)return;status=next;const sync=()=>setLocationState(next.state==='granted'?'granted':next.state==='denied'?'denied':'prompt');sync();next.onchange=sync;}).catch(()=>{if(!disposed)setLocationState('prompt');});
    return()=>{disposed=true;if(status)status.onchange=null;window.removeEventListener('online',onOnline);window.removeEventListener('offline',onOffline);};
  },[]);

  function requestLocation(){
    if(!navigator.geolocation){setLocationState('unavailable');return;}
    setLocationState('requesting');navigator.geolocation.getCurrentPosition(()=>setLocationState('granted'),()=>setLocationState('denied'),{enableHighAccuracy:true,maximumAge:5_000,timeout:12_000});
  }
  function next(){setIndex((value)=>Math.min(STEPS.length-1,value+1));}
  function finish(){updatePreferences({advisoryAlerts:advisories});try{window.localStorage.setItem(FIRST_RUN_STORAGE_KEY,'1');}catch{}onComplete();}

  return <main className="firstRunShell" data-testid="first-run-experience">
    <section className="firstRunHero" aria-hidden="true"><div className="firstRunHorizon"/><div className="firstRunRoad"><i/><i/><i/></div><span className="firstRunVehicle"><CarFront/></span><div className="firstRunBrand"><span><CarFront/></span><strong>KINGMAST</strong><small>{tx('Driver safety · v0.0.8','An toàn người lái · v0.0.8')}</small></div></section>
    <section className="firstRunPanel" aria-labelledby="first-run-title"><div className="firstRunProgress" aria-label={tx(`Setup step ${index+1} of ${STEPS.length}`,`Bước thiết lập ${index+1}/${STEPS.length}`)}>{STEPS.map((item,stepIndex)=><i key={item} className={stepIndex<=index?'isActive':''}/>)}</div>
      {step==='welcome'?<div className="firstRunStep"><span className="firstRunGlyph safe"><ShieldCheck/></span><p className="eyebrow">{tx('Welcome to KINGMAST','Chào mừng đến KINGMAST')}</p><h1 id="first-run-title">{tx('Safety first. Minimal setup.','An toàn trước tiên. Thiết lập tối giản.')}</h1><p>{tx('KINGMAST is a warning-only driver assistance system. It does not brake, steer, accelerate, or write vehicle-control CAN commands.','KINGMAST là hệ thống hỗ trợ lái chỉ cảnh báo. Hệ thống không phanh, đánh lái, tăng ga hoặc ghi lệnh điều khiển lên CAN của xe.')}</p><div className="firstRunActions" role="group" aria-label={tx('Language','Ngôn ngữ')}><button type="button" className="firstRunSecondary" aria-pressed={profile.locale==='en-US'} onClick={()=>updateProfile({locale:'en-US'})}>English</button><button type="button" className="firstRunSecondary" aria-pressed={profile.locale==='vi-VN'} onClick={()=>updateProfile({locale:'vi-VN'})}>Tiếng Việt</button></div><div className="firstRunSafety"><AlertTriangle/><span><strong>{tx('Critical collision and vulnerable-road-user warnings always stay active.','Cảnh báo va chạm nghiêm trọng và người tham gia giao thông dễ tổn thương luôn được bật.')}</strong><small>{tx('Optional road, camera and connected-road advisories can be changed later while parked.','Các cảnh báo đường, camera và đường kết nối tùy chọn có thể thay đổi sau khi xe đang đỗ.')}</small></span></div><button className="firstRunPrimary" type="button" onClick={next}>{tx('Continue','Tiếp tục')} <ChevronRight/></button></div>:null}
      {step==='location'?<div className="firstRunStep"><span className={`firstRunGlyph ${locationState==='granted'?'safe':''}`}><LocateFixed/></span><p className="eyebrow">{tx('Location','Vị trí')}</p><h1 id="first-run-title">{location.title}</h1><p>{location.message}</p><div className="firstRunPermission"><MapPinned/><span><strong>{tx('No coordinate is stored by this setup screen.','Màn hình thiết lập này không lưu tọa độ.')}</strong><small>{tx('Trip/event retention remains a separate parked-mode privacy choice.','Lưu hành trình/sự kiện vẫn là một tùy chọn quyền riêng tư riêng khi xe đang đỗ.')}</small></span></div><div className="firstRunActions">{locationState!=='granted'&&locationState!=='unavailable'?<button type="button" className="firstRunSecondary" disabled={locationState==='requesting'} onClick={requestLocation}>{locationState==='requesting'?tx('Waiting for permission…','Đang chờ quyền…'):tx('Allow location','Cho phép vị trí')}</button>:null}<button type="button" className="firstRunPrimary" onClick={next}>{locationState==='granted'?tx('Continue','Tiếp tục'):tx('Continue in limited mode','Tiếp tục ở chế độ giới hạn')} <ChevronRight/></button></div></div>:null}
      {step==='connectivity'?<div className="firstRunStep"><span className={`firstRunGlyph ${online?'safe':'caution'}`}>{online?<Wifi/>:<WifiOff/>}</span><p className="eyebrow">{tx('Connectivity','Kết nối')}</p><h1 id="first-run-title">{online?tx('Host network available','Mạng của thiết bị chủ đã sẵn sàng'):tx('Offline mode is ready','Chế độ ngoại tuyến đã sẵn sàng')}</h1><p>{online?tx('Online map, traffic-camera and connected-road services can be used when providers are available.','Bản đồ trực tuyến, camera giao thông và dịch vụ đường kết nối có thể dùng khi nhà cung cấp khả dụng.'):tx('Primary on-vehicle warnings remain available. Online route search and connected-road context pause until connectivity returns.','Các cảnh báo chính trên xe vẫn hoạt động. Tìm tuyến trực tuyến và ngữ cảnh đường kết nối tạm dừng cho tới khi có mạng trở lại.')}</p><div className="firstRunSafety"><ShieldCheck/><span><strong>{tx('Safety does not depend on cloud availability.','An toàn không phụ thuộc vào việc cloud có khả dụng hay không.')}</strong><small>{tx('When offline, verify posted signs and direct road conditions. Cached guidance is labeled when used.','Khi ngoại tuyến, hãy kiểm tra biển báo và điều kiện đường thực tế. Hướng dẫn từ bộ nhớ đệm sẽ được ghi rõ khi sử dụng.')}</small></span></div><button type="button" className="firstRunPrimary" onClick={next}>{tx('Continue','Tiếp tục')} <ChevronRight/></button></div>:null}
      {step==='ready'?<div className="firstRunStep"><span className="firstRunGlyph safe"><Check/></span><p className="eyebrow">{tx('Ready','Sẵn sàng')}</p><h1 id="first-run-title">{tx('Your driving view is configured.','Màn hình lái xe đã được cấu hình.')}</h1><p>{tx('Keep essential warnings visible while driving. Detailed network, privacy, history and calibration controls remain parked-only.','Giữ các cảnh báo thiết yếu luôn hiển thị khi lái. Điều khiển chi tiết về mạng, quyền riêng tư, lịch sử và hiệu chuẩn chỉ mở khi xe đang đỗ.')}</p><label className="firstRunToggle"><span><strong>{tx('Optional road advisories','Cảnh báo đường tùy chọn')}</strong><small>{tx('Camera, speed-camera and connected-road context. Critical safety warnings are unaffected.','Camera, camera tốc độ và ngữ cảnh đường kết nối. Cảnh báo an toàn quan trọng không bị ảnh hưởng.')}</small></span><button type="button" role="switch" aria-label={tx('Optional road advisories during first-run setup','Cảnh báo đường tùy chọn trong thiết lập ban đầu')} aria-checked={advisories} className={`appleSwitch ${advisories?'isOn':''}`} onClick={()=>setAdvisories((value)=>!value)}><span/></button></label><button className="firstRunPrimary" type="button" onClick={finish}>{tx('Start KINGMAST','Bắt đầu KINGMAST')} <ChevronRight/></button></div>:null}
    </section>
  </main>;
}
