'use client';

import { useEffect,useMemo,useState,type FormEvent } from 'react';
import { Bike,BusFront,Camera,CarFront,CircleDotDashed,Gauge,LocateFixed,MapPin,Navigation,Route,Search,TriangleAlert,Truck,UserRound,X } from 'lucide-react';
import type { DetectedObject,ObjectKind,VehiclePosition } from '@kingmast/contracts';
import type { RoadContextController } from '../lib/road-context';
import { cameraIsDriverRelevant,cameraLabel,routeAwareCameras,routeProgress } from '../lib/driver-context';
import { useDriverProfile } from '../lib/use-driver-profile';
import { useI18n } from '../lib/i18n';
import { formatDistance,speedAriaLabel,speedUnit,speedValue } from '../lib/units';
import NativeNavigationMap from './NativeNavigationMap';
import RouteRecoveryPanel from './RouteRecoveryPanel';
import styles from './GpsSafetyMap.module.css';

const ICONS={person:UserRound,car:CarFront,motorcycle:Bike,bicycle:Bike,truck:Truck,bus:BusFront,obstacle:TriangleAlert,unknown:CircleDotDashed} satisfies Record<ObjectKind,typeof CarFront>;
export function ObjectGlyph({kind}:{kind:ObjectKind}){const Icon=ICONS[kind];return <Icon aria-hidden="true" strokeWidth={1.8}/>;}

export default function GpsSafetyMap({vehicle,objects,road,compact=false,allowSearch=true}:{vehicle:VehiclePosition;objects:DetectedObject[];road:RoadContextController;compact?:boolean;allowSearch?:boolean}){
  const[query,setQuery]=useState('');const[headingUp,setHeadingUp]=useState(true);const[online,setOnline]=useState(true);const[endConfirm,setEndConfirm]=useState(false);const{profile}=useDriverProfile();const{isVietnamese}=useI18n();const tx=(en:string,vi:string)=>isVietnamese?vi:en;const units=profile.units;const limit=road.context?.speedLimit.currentKmh??null;const over=road.context?.compliance==='over-limit';const routeCameras=useMemo(()=>routeAwareCameras(vehicle,road.route,road.context?.cameras??[]),[vehicle,road.route,road.context?.cameras]);const progress=routeProgress(vehicle,road.route);const searchAllowed=allowSearch&&online;
  useEffect(()=>{const sync=()=>setOnline(navigator.onLine);sync();window.addEventListener('online',sync);window.addEventListener('offline',sync);return()=>{window.removeEventListener('online',sync);window.removeEventListener('offline',sync);};},[]);
  useEffect(()=>{if(!road.route)setEndConfirm(false);},[road.route]);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!searchAllowed)return;await road.searchPlaces(query);};
  const choosePlace=async(place:(typeof road.places)[number])=>{if(!searchAllowed)return;setQuery('');await road.navigate(place.position,place);};
  const mapCameras=road.route?routeCameras.map((item)=>item.camera):road.context?.cameras??[];

  return <div className={styles.wrapper}>
    <div className={styles.mapFrame}>
      <NativeNavigationMap vehicle={vehicle} objects={objects} cameras={mapCameras} route={road.route} headingUp={headingUp} compact={compact}/>
      <div className={styles.mapTopLeft}><span><LocateFixed strokeWidth={1.8}/>{vehicle.source==='device-gps'?'GPS':vehicle.source==='gnss'?'GNSS':'DEMO'}</span>{road.routeFromCache?<span>{tx('Cached route','Tuyến đã lưu')}</span>:null}{!online?<span>{tx('Offline','Ngoại tuyến')}</span>:null}</div>
      <button type="button" className={styles.headingButton} onClick={()=>setHeadingUp((value)=>!value)} aria-pressed={headingUp}><Navigation strokeWidth={1.8}/>{headingUp?tx('Heading up','Theo hướng xe'):tx('North up','Hướng Bắc lên')}</button>
      <div className={`${styles.speedLimit} ${over?styles.overLimit:''}`} aria-label={speedAriaLabel(limit,units)}><strong>{limit===null?'—':speedValue(limit,units)}</strong><small>{speedUnit(units)}</small></div>
      {!compact?<div className={styles.cameraCount}><Camera strokeWidth={1.7}/>{road.route?tx(`${routeCameras.length} on route`,`${routeCameras.length} trên tuyến`):tx(`${road.context?.cameras.length??0} nearby`,`${road.context?.cameras.length??0} gần đây`)}</div>:null}
    </div>

    {!compact?<section className={styles.navigationPanel} aria-label={tx('Navigation','Dẫn đường')}>
      <RouteRecoveryPanel road={road} online={online}/>
      <form className={`${styles.searchBar} ${!searchAllowed?styles.searchLocked:''}`} onSubmit={submit}><Search strokeWidth={1.9}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder={!online?tx('Destination search unavailable offline','Không thể tìm điểm đến khi ngoại tuyến'):allowSearch?tx('Where to?','Đi đâu?'):tx('Destination changes available while parked','Chỉ đổi điểm đến khi xe đang đỗ')} aria-label={tx('Search destination','Tìm điểm đến')} autoComplete="off" disabled={!searchAllowed}/><button type="submit" disabled={!searchAllowed||road.searchLoading||query.trim().length<2}>{road.searchLoading?tx('Searching…','Đang tìm…'):tx('Search','Tìm')}</button></form>
      {searchAllowed&&road.places.length>0&&query?<div className={styles.searchResults}>{road.places.map((place)=><button type="button" key={place.id} onClick={()=>void choosePlace(place)}><MapPin strokeWidth={1.8}/><span><strong>{place.name}</strong><small>{place.subtitle??tx('Destination','Điểm đến')}</small></span></button>)}</div>:null}
      {searchAllowed&&query.length===0&&road.recentPlaces.length>0&&!road.route?<div className={styles.recents}><span>{tx('Recent','Gần đây')}</span>{road.recentPlaces.slice(0,3).map((place)=><button type="button" key={place.id} onClick={()=>void choosePlace(place)}><MapPin strokeWidth={1.7}/><strong>{place.name}</strong></button>)}</div>:null}
      <div className={styles.contextRow}><div><span>{tx('Speed limit','Giới hạn tốc độ')}</span><strong className={over?styles.warningText:''}>{limit===null?'—':speedValue(limit,units)}</strong><small>{road.context?.speedLimit.roadName??tx('Current road','Đường hiện tại')} · {speedUnit(units)}</small></div><div><span>{tx('Your speed','Tốc độ xe')}</span><strong>{speedValue(vehicle.speedKmh,units)}</strong><small>{over?tx('Reduce speed','Giảm tốc'):road.context?.compliance==='near-limit'?tx('Near limit','Gần giới hạn'):tx(`Within limit · ${speedUnit(units)}`,`Trong giới hạn · ${speedUnit(units)}`)}</small></div><div><span>{tx('Route cameras','Camera trên tuyến')}</span><strong>{road.route?routeCameras.filter((item)=>cameraIsDriverRelevant(item.camera)).length:road.context?.cameras.length??0}</strong><small>{road.route?tx('Matched to route','Khớp với tuyến'):tx('Nearby context','Ngữ cảnh gần đây')}</small></div></div>
      {road.route?<div className={styles.routeSummary}><div className={styles.routeHeadline}><Navigation strokeWidth={1.9}/><span><strong>{progress?formatDistance(progress.remainingM,units):formatDistance(road.route.distanceM,units)}</strong><small>{progress?tx(`${Math.max(1,Math.round(progress.etaS/60))} min remaining`,`${Math.max(1,Math.round(progress.etaS/60))} phút còn lại`):tx(`${Math.round(road.route.durationS/60)} min`,`${Math.round(road.route.durationS/60)} phút`)}</small></span><button type="button" onClick={()=>setEndConfirm(true)} aria-label={tx('End route','Kết thúc tuyến')}><X strokeWidth={1.9}/></button></div><div className={styles.progressTrack}><i style={{width:`${Math.round((progress?.progress??0)*100)}%`}}/></div>{endConfirm?<div className={styles.routeEndConfirm} role="group" aria-label={tx('Confirm ending route guidance','Xác nhận kết thúc dẫn đường')}><span><strong>{tx('End route guidance?','Kết thúc dẫn đường?')}</strong><small>{tx('Your destination and active guidance will be cleared from this HMI.','Điểm đến và hướng dẫn đang hoạt động sẽ bị xóa khỏi HMI này.')}</small></span><div><button type="button" onClick={()=>setEndConfirm(false)}>{tx('Keep guidance','Giữ dẫn đường')}</button><button type="button" className={styles.routeEndPrimary} onClick={()=>{road.clearRoute();setEndConfirm(false);}}>{tx('End guidance','Kết thúc')}</button></div></div>:null}{road.route.steps.slice(0,3).map((step,index)=><p key={`${step.instruction}-${index}`}><b>{index+1}</b><span>{step.instruction}</span><small>{formatDistance(step.distanceM,units)}</small></p>)}</div>:<div className={styles.emptyRoute}><Route strokeWidth={1.8}/><span><strong>{online?tx('Ready to navigate','Sẵn sàng dẫn đường'):tx('Offline navigation','Dẫn đường ngoại tuyến')}</strong><small>{online?tx('Set a destination before driving.','Đặt điểm đến trước khi lái.'):tx('Reconnect to search for a new destination.','Kết nối lại để tìm điểm đến mới.')}</small></span></div>}
      {routeCameras.find((item)=>cameraIsDriverRelevant(item.camera))?<div className={styles.cameraAhead}><Camera strokeWidth={1.8}/><span><strong>{cameraLabel(routeCameras.find((item)=>cameraIsDriverRelevant(item.camera))!.camera)}</strong><small>{tx(`${formatDistance(routeCameras.find((item)=>cameraIsDriverRelevant(item.camera))!.routeDistanceM,units)} ahead on route`,`${formatDistance(routeCameras.find((item)=>cameraIsDriverRelevant(item.camera))!.routeDistanceM,units)} phía trước trên tuyến`)}</small></span></div>:null}
      <p className={styles.sourceNote}>{!online?tx('Offline mode: online search, rerouting and connected-road context are paused. Existing on-vehicle safety warnings remain active.','Chế độ ngoại tuyến: tìm kiếm trực tuyến, tính lại tuyến và ngữ cảnh đường kết nối đang tạm dừng. Các cảnh báo an toàn hiện có trên xe vẫn hoạt động.'):road.error?tx('Road information is temporarily degraded. Verify posted signs.','Thông tin đường tạm thời bị suy giảm. Hãy kiểm tra biển báo thực tế.'):tx('Speed limits combine mapped road data with high-confidence sign recognition. Camera coverage varies by public or authorized provider.','Giới hạn tốc độ kết hợp dữ liệu bản đồ với nhận dạng biển báo có độ tin cậy cao. Phạm vi camera phụ thuộc nguồn công khai hoặc nhà cung cấp được ủy quyền.')}</p>
    </section>:null}
  </div>;
}
