'use client';

import { AlertTriangle,Bell,BellOff,CarFront,CloudRain,Construction,Navigation,Route,School,ShieldCheck,WifiOff } from 'lucide-react';
import { useEffect,useMemo,useRef,useState } from 'react';
import type { ConnectedRoadAdvisory,NavigationRoute,TelemetryFrame } from '@kingmast/contracts';
import KingmastV5 from './KingmastV5';
import StartupExperience from './StartupExperience';
import FirstRunExperience,{FIRST_RUN_STORAGE_KEY} from './FirstRunExperience';
import SystemLifecycleStatus from './SystemLifecycleStatus';
import { createSimulationFrame } from '../lib/telemetry';
import type { KingmastTelemetryEventDetail } from '../lib/realtime';
import { useConnectedRoadContext,useConnectedRoadProviderStatus } from '../lib/connected-road';
import { primaryRoadEvent,type RoadEventPresentation } from '../lib/road-event-presentation';
import { useHmiPreferences } from '../lib/use-hmi-preferences';
import { useDriverProfile } from '../lib/use-driver-profile';
import { useI18n } from '../lib/i18n';
import { isNavigationRoute } from '../lib/persisted-navigation';
import { convertMetricText,formatDistance } from '../lib/units';

const ROUTE_KEYS=['kingmast:v006:route','kingmast:v25:route'];
const LIVE_FRAME_MAX_AGE_MS=4_000;
const TRANSIENT_NOTICE_MS=2_200;

function readCachedRoute():NavigationRoute|null{try{for(const key of ROUTE_KEYS){const raw=window.localStorage.getItem(key);if(!raw)continue;const parsed=JSON.parse(raw) as {route?:unknown};if(isNavigationRoute(parsed?.route))return parsed.route;window.localStorage.removeItem(key);}}catch{}return null;}
function advisoryIcon(item:ConnectedRoadAdvisory){if(item.category==='school-zone')return School;if(item.category==='construction-zone')return Construction;if(item.category==='weather'||item.category==='road-hazard')return CloudRain;if(item.category==='highway-exit'||item.category==='lane-guidance')return Route;if(item.category==='spat')return Bell;if(item.category==='emergency-vehicle')return CarFront;return AlertTriangle;}
function eventIcon(item:RoadEventPresentation){if(item.kind==='roadwork')return Construction;if(item.kind==='spat')return Bell;if(item.kind==='emergency')return CarFront;if(item.kind==='arrival')return Navigation;return AlertTriangle;}

function LaneMini({event}:{event:RoadEventPresentation}){const{isVietnamese}=useI18n();if(!event.laneCount)return null;const count=Math.min(5,Math.max(1,event.laneCount));const preferred=new Set(event.preferredLaneIndexes??[]);const preferredText=[...preferred].map((value)=>value+1).join(', ')||(isVietnamese?'chưa xác định':'not resolved');return <div className="laneMini" aria-label={isVietnamese?`${event.laneCount} làn. Làn ưu tiên ${preferredText}.`:`${event.laneCount} lanes. Preferred lanes ${preferredText}.`}>{Array.from({length:count},(_,index)=><span key={index} className={`${event.currentLaneIndex===index?'isCurrent ':''}${preferred.has(index)?'isPreferred':''}`}><b>{index+1}</b></span>)}</div>;}
function ConnectedEventHero({event}:{event:RoadEventPresentation}){const Icon=eventIcon(event);const{profile}=useDriverProfile();const{isVietnamese}=useI18n();const units=profile.units;const meta=event.meta?convertMetricText(event.meta,units):event.distanceM===null?null:formatDistance(event.distanceM,units);return <div className={`connectedEventHero event-${event.kind} tone-${event.tone}`} data-road-event={event.kind}><span><Icon/></span><span><strong>{event.title}</strong><small>{convertMetricText(event.message,units)}</small></span>{event.kind==='roadwork'?<LaneMini event={event}/>:<em>{meta??(isVietnamese?'Khuyến cáo':'Advisory')}</em>}</div>;}
function ConnectedAdvisoryNotice({item,units}:{item:ConnectedRoadAdvisory;units:'metric'|'imperial'}){const Icon=advisoryIcon(item);return <div className={`connectedAdvisory severity-${item.severity}`}><Icon strokeWidth={1.9}/><span><strong>{item.title}</strong><small>{convertMetricText(item.message,units)}</small></span></div>;}
function DegradedConnectedRoad({title,message}:{title:string;message:string}){const{isVietnamese}=useI18n();return <aside className="connectedRoadHud connectedRoadDegraded" aria-label={isVietnamese?'Trạng thái thông tin đường kết nối':'Connected road intelligence status'} role="status"><div className="connectedRoadHead"><span><WifiOff strokeWidth={1.8}/><strong>{title}</strong><small>{isVietnamese?'khuyến cáo không khả dụng':'advisory unavailable'}</small></span></div><div className="connectedClear"><AlertTriangle/><span><strong>{title}</strong><small>{message}</small></span></div><div className="connectedSafetyNote"><AlertTriangle/> {isVietnamese?'Tiếp tục dựa vào biển báo, tín hiệu và quan sát trực tiếp mặt đường.':'Continue using posted signs, signals and direct road observation.'}</div></aside>;}
function TransientNotice({noticeKey,persistent=false,children}:{noticeKey:string;persistent?:boolean;children:React.ReactNode}){const[visible,setVisible]=useState(true);useEffect(()=>{setVisible(true);if(persistent)return;const timer=window.setTimeout(()=>setVisible(false),TRANSIENT_NOTICE_MS);return()=>window.clearTimeout(timer);},[noticeKey,persistent]);return visible?<>{children}</>:null;}

function ConnectedRoadHud({advisoryAlerts,networkOnline}:{advisoryAlerts:boolean;networkOnline:boolean}){
  const[sequence,setSequence]=useState(0);const[route,setRoute]=useState<NavigationRoute|null>(null);const[liveFrame,setLiveFrame]=useState<TelemetryFrame|null>(null);const[nowMs,setNowMs]=useState(()=>Date.now());const liveFrameAtRef=useRef(0);const{profile}=useDriverProfile();const{isVietnamese}=useI18n();const tx=(en:string,vi:string)=>isVietnamese?vi:en;const units=profile.units;
  useEffect(()=>{const timer=window.setInterval(()=>setSequence((value)=>value+1),2800);return()=>window.clearInterval(timer);},[]);useEffect(()=>{const timer=window.setInterval(()=>setNowMs(Date.now()),1000);return()=>window.clearInterval(timer);},[]);useEffect(()=>{const load=()=>setRoute(readCachedRoute());load();const timer=window.setInterval(load,2_000);return()=>window.clearInterval(timer);},[]);
  useEffect(()=>{const onTelemetry=(event:Event)=>{const detail=(event as CustomEvent<KingmastTelemetryEventDetail>).detail;if(!detail?.frame)return;liveFrameAtRef.current=Date.now();setLiveFrame(detail.frame);};window.addEventListener('kingmast:telemetry',onTelemetry);return()=>window.removeEventListener('kingmast:telemetry',onTelemetry);},[]);
  const simulated=useMemo(()=>createSimulationFrame(sequence),[sequence]);const hasSeenLive=liveFrame!==null;const liveFresh=hasSeenLive&&nowMs-liveFrameAtRef.current<=LIVE_FRAME_MAX_AGE_MS;const frame=hasSeenLive?liveFrame:simulated;const contextVehicle=hasSeenLive?(liveFresh?liveFrame.vehicle:null):simulated.vehicle;const collisionCritical=liveFresh||!hasSeenLive?frame.alerts.some((item)=>item.severity==='critical'):false;const enabled=advisoryAlerts&&networkOnline;const connected=useConnectedRoadContext(contextVehicle,route,collisionCritical,enabled);const providerHealth=useConnectedRoadProviderStatus(enabled);const moving=frame.vehicle.source!=='simulator'&&frame.vehicle.speedKmh>=5;
  const trustIssue=providerHealth.providers.find((item)=>item.state==='degraded'&&!item.liveV2xTrusted&&item.security!==null)??null;const trustExpiring=providerHealth.providers.find((item)=>item.security?.trustStatus==='expiring'&&item.liveV2xTrusted)??null;const driverTrustIssue=moving?null:trustIssue;const driverTrustExpiring=moving?null:trustExpiring;
  if(!advisoryAlerts||!networkOnline)return null;
  if(hasSeenLive&&!liveFresh)return <TransientNotice noticeKey="connected-road-stale"><DegradedConnectedRoad title={tx('Connected road paused','Đã tạm dừng đường kết nối')} message={tx('Vehicle telemetry is stale. KINGMAST will not substitute simulator road context over a live vehicle session.','Telemetry xe đã cũ. KINGMAST không thay thế ngữ cảnh đường của xe thật bằng dữ liệu mô phỏng trong một phiên xe trực tiếp.')}/></TransientNotice>;
  if(connected.error&&!connected.context)return <TransientNotice noticeKey={`connected-road-error:${connected.error}`}><DegradedConnectedRoad title={tx('Connected road unavailable','Đường kết nối không khả dụng')} message={tx('Online road context is paused. Primary warnings remain active.','Ngữ cảnh đường trực tuyến đang tạm dừng. Các cảnh báo chính vẫn hoạt động.')}/></TransientNotice>;
  if(!connected.context)return null;
  const context=connected.context;const hero=primaryRoadEvent(context,frame.vehicle,route,nowMs);const heroCategory=hero?.kind==='roadwork'?'construction-zone':hero?.kind==='spat'?'spat':hero?.kind==='emergency'?'emergency-vehicle':null;const primaryAdvisory=context.advisories.find((item)=>item.category!==heroCategory)??null;const criticalHero=hero?.tone==='critical';const criticalAdvisory=primaryAdvisory?.severity==='critical';const critical=criticalHero||criticalAdvisory;const noticeKey=criticalHero&&hero?`event:${hero.kind}:${hero.title}`:criticalAdvisory&&primaryAdvisory?`advisory:${primaryAdvisory.dedupeKey}`:driverTrustIssue?`trust:${driverTrustIssue.providerId}:${driverTrustIssue.security?.trustStatus}`:hero?`event:${hero.kind}:${hero.title}`:primaryAdvisory?`advisory:${primaryAdvisory.dedupeKey}`:driverTrustExpiring?`trust-expiring:${driverTrustExpiring.providerId}`:'';
  if(!driverTrustIssue&&!driverTrustExpiring&&!hero&&!primaryAdvisory)return null;
  return <TransientNotice noticeKey={noticeKey} persistent={critical}><aside className={`connectedRoadHud connectedRoadCompact coverage-${context.coverage} ${hero?'hasRoadEvent':''}`} aria-label={tx('Connected road alert','Cảnh báo đường kết nối')} role={critical?'alert':'status'} data-attention={critical?'critical':'transient'}><div className="connectedRoadHead"><span><ShieldCheck strokeWidth={1.8}/><strong>{tx('Connected road','Đường kết nối')}</strong><small>{context.coverage.replaceAll('-',' ')}</small></span>{driverTrustIssue?<em data-testid="v2x-trust-warning">{tx('V2X trust degraded','Tin cậy V2X suy giảm')}</em>:driverTrustExpiring?<em>{tx('Certificate expiring','Chứng thư sắp hết hạn')}</em>:null}</div>{criticalHero&&hero?<ConnectedEventHero event={hero}/>:criticalAdvisory&&primaryAdvisory?<ConnectedAdvisoryNotice item={primaryAdvisory} units={units}/>:driverTrustIssue?<div className="connectedAdvisory severity-caution" data-testid="v2x-trust-detail"><AlertTriangle/><span><strong>{tx('Live V2X ignored','Đã bỏ qua V2X trực tiếp')}</strong><small>{driverTrustIssue.providerId}: {tx('provider trust must be restored.','cần khôi phục tin cậy nhà cung cấp.')}</small></span></div>:hero?<ConnectedEventHero event={hero}/>:primaryAdvisory?<ConnectedAdvisoryNotice item={primaryAdvisory} units={units}/>:<div className="connectedAdvisory severity-caution"><AlertTriangle/><span><strong>{tx('V2X certificate expiring','Chứng thư V2X sắp hết hạn')}</strong><small>{driverTrustExpiring?.providerId}</small></span></div>}</aside></TransientNotice>;
}

export default function KingmastV006(){
  const[bootComplete,setBootComplete]=useState(false);const[firstRunComplete,setFirstRunComplete]=useState<boolean|null>(null);const[ambient,setAmbient]=useState<'unknown'|'day'|'night'>('unknown');const[networkOnline,setNetworkOnline]=useState(true);const{preferences}=useHmiPreferences();const{isVietnamese}=useI18n();const tx=(en:string,vi:string)=>isVietnamese?vi:en;
  useEffect(()=>{try{setFirstRunComplete(window.localStorage.getItem(FIRST_RUN_STORAGE_KEY)==='1');}catch{setFirstRunComplete(false);}},[]);
  useEffect(()=>{const update=()=>{const hour=new Date().getHours();setAmbient(hour>=7&&hour<18?'day':'night');};update();const timer=window.setInterval(update,10*60_000);return()=>window.clearInterval(timer);},[]);
  useEffect(()=>{const sync=()=>setNetworkOnline(navigator.onLine);sync();window.addEventListener('online',sync);window.addEventListener('offline',sync);return()=>{window.removeEventListener('online',sync);window.removeEventListener('offline',sync);};},[]);
  if(!bootComplete)return <StartupExperience onComplete={()=>setBootComplete(true)}/>;
  if(firstRunComplete===null)return <div className="firstRunShell" aria-label={tx('Loading KINGMAST setup','Đang tải thiết lập KINGMAST')}/>;
  if(!firstRunComplete)return <FirstRunExperience onComplete={()=>setFirstRunComplete(true)}/>;
  return <div className={`kingmastExperience ambient-${ambient} ${preferences.advisoryAlerts?'':'advisories-off'} ${networkOnline?'':'isOffline'}`}><KingmastV5/><SystemLifecycleStatus/>{!networkOnline?<TransientNotice noticeKey="network-offline"><div className="networkModeBanner transientSystemNotice" role="status" data-testid="offline-mode"><WifiOff/><span><strong>{tx('Offline mode','Chế độ ngoại tuyến')}</strong><small>{tx('Online services paused. Primary on-vehicle warnings remain active.','Dịch vụ trực tuyến đang tạm dừng. Các cảnh báo chính trên xe vẫn hoạt động.')}</small></span><button type="button" onClick={()=>setNetworkOnline(navigator.onLine)}>{tx('Retry','Thử lại')}</button></div></TransientNotice>:null}{!preferences.advisoryAlerts?<TransientNotice noticeKey="advisories-off"><div className="advisoryModePill transientSystemNotice" role="status" data-testid="advisory-mode-off"><BellOff/><span><strong>{tx('Optional advisories off','Đã tắt cảnh báo tùy chọn')}</strong><small>{tx('Critical safety warnings remain active','Cảnh báo an toàn quan trọng vẫn hoạt động')}</small></span></div></TransientNotice>:null}<ConnectedRoadHud advisoryAlerts={preferences.advisoryAlerts} networkOnline={networkOnline}/></div>;
}
