'use client';

import { Camera, CheckCircle2, Radar, RefreshCw, Satellite, ShieldCheck, TriangleAlert, Wrench } from 'lucide-react';
import { useState } from 'react';
import { useSensorMaintenance, type MaintenanceSensorId, type SensorMaintenanceRecord } from '../lib/use-sensor-maintenance';
import { useI18n } from '../lib/i18n';

function SensorIcon({id}:{id:MaintenanceSensorId}) { const Icon=id==='camera-front'?Camera:id==='gnss-imu'?Satellite:Radar; return <Icon strokeWidth={1.8}/>; }

export default function SensorMaintenancePanel(){
  const maintenance=useSensorMaintenance();const{t,isVietnamese}=useI18n();
  const[pending,setPending]=useState<{sensor:SensorMaintenanceRecord;action:'calibrate'|'replacement'}|null>(null);
  const statusLabel=(sensor:SensorMaintenanceRecord)=>sensor.state==='ready'?t('common.ready'):sensor.state==='calibration-required'?t('common.calibrationRequired'):sensor.state==='service-required'?(isVietnamese?'Cần bảo dưỡng':'Service required'):t('device.statusUnavailable');
  async function confirm(){if(!pending)return;const ok=pending.action==='calibrate'?await maintenance.calibrate(pending.sensor.id):await maintenance.verifyReplacement(pending.sensor.id);if(ok)setPending(null);}
  return <section className="systemCard" data-testid="sensor-maintenance">
    <div className="systemCardHeader"><span><Wrench/><span><strong>{isVietnamese?'Hiệu chuẩn & thay thế cảm biến':'Sensor calibration & replacement'}</strong><small>{isVietnamese?'Quy trình bảo dưỡng khi xe đang đỗ · không có quyền điều khiển xe':'Parked-only service workflow · no vehicle-control authority'}</small></span></span><b>{maintenance.mode==='native'?(isVietnamese?'Dịch vụ xe':'Vehicle service'):(isVietnamese?'Máy chủ quản lý':'Host managed')}</b></div>
    {maintenance.mode==='host-managed'?<div className="systemNotice"><ShieldCheck/><span><strong>{t('device.hostManaged')}</strong><small>{isVietnamese?'Bản xem trước trên trình duyệt không tự nhận hiệu chuẩn thành công. Phần cứng thật phải cung cấp native maintenance bridge và kiểm tra điều kiện xe đứng yên/bảo dưỡng.':'The browser preview does not claim sensor calibration success. Production hardware must expose the native maintenance bridge and enforce stationary/service prerequisites.'}</small></span></div>:null}
    <div className="sensorMaintenanceList">{maintenance.sensors.map((sensor)=><div className={`sensorMaintenanceRow state-${sensor.state}`} key={sensor.id}><span className="maintenanceGlyph"><SensorIcon id={sensor.id}/></span><span><strong>{sensor.label}</strong><small>{sensor.detail??(sensor.lastCalibrationAtMs?(isVietnamese?`Hiệu chuẩn gần nhất ${new Date(sensor.lastCalibrationAtMs).toLocaleDateString('vi-VN')}`:`Last calibrated ${new Date(sensor.lastCalibrationAtMs).toLocaleDateString()}`):(isVietnamese?'Chưa có thời gian hiệu chuẩn':'No calibration timestamp'))}</small></span><em>{statusLabel(sensor)}</em>{maintenance.mode==='native'?<div className="maintenanceActions">{sensor.state==='calibration-required'?<button type="button" disabled={maintenance.busySensorId!==null} onClick={()=>setPending({sensor,action:'calibrate'})}>{isVietnamese?'Hiệu chuẩn':'Calibrate'}</button>:null}<button type="button" disabled={maintenance.busySensorId!==null} onClick={()=>setPending({sensor,action:'replacement'})}>{isVietnamese?'Kiểm tra thay thế':'Replacement check'}</button></div>:null}</div>)}</div>
    {pending?<div className="maintenanceConfirm" role="group" aria-label={isVietnamese?'Xác nhận tác vụ bảo dưỡng cảm biến':'Confirm sensor maintenance action'}><TriangleAlert/><span><strong>{pending.action==='calibrate'?(isVietnamese?`Hiệu chuẩn ${pending.sensor.label}?`:`Calibrate ${pending.sensor.label}?`):(isVietnamese?`Xác minh thay thế ${pending.sensor.label}?`:`Verify replacement for ${pending.sensor.label}?`)}</strong><small>{pending.action==='calibrate'?(isVietnamese?'Giữ xe đỗ trên bề mặt bảo dưỡng và làm theo hướng dẫn của native host. Kết quả hiệu chuẩn phải đến từ dịch vụ xe, không phải web UI.':'Keep the vehicle parked on the service surface and follow the native host instructions. Calibration completion must come from the vehicle service, not the web UI.'):(isVietnamese?'Chỉ dùng sau khi đã thao tác phần cứng thực tế. Xác minh thay thế không bỏ qua yêu cầu hiệu chuẩn hoặc kiểm tra.':'Use this only after physical service work. Replacement verification does not bypass required calibration or inspection.')}</small></span><div><button type="button" onClick={()=>setPending(null)}>{t('common.cancel')}</button><button type="button" className="systemPrimary" onClick={()=>void confirm()}>{maintenance.busySensorId?<RefreshCw className="isSpinning"/>:<CheckCircle2/>}{pending.action==='calibrate'?t('common.startCalibration'):(isVietnamese?'Xác minh thay thế':'Verify replacement')}</button></div></div>:null}
    {maintenance.error?<div className="systemError" role="status"><TriangleAlert/><span>{maintenance.error}</span></div>:null}
    <button type="button" className="systemRefresh" onClick={()=>void maintenance.refresh()}><RefreshCw/> {isVietnamese?'Làm mới trạng thái cảm biến':'Refresh sensor state'}</button>
  </section>;
}
