'use client';

import { CheckCircle2, Download, RefreshCw, RotateCcw, ShieldCheck, TriangleAlert } from 'lucide-react';
import { useState } from 'react';
import { useSoftwareUpdate } from '../lib/use-software-update';
import { useI18n } from '../lib/i18n';

export default function SoftwareUpdatePanel(){
  const updates=useSoftwareUpdate();const{t,isVietnamese}=useI18n();
  const[confirm,setConfirm]=useState<'install'|'rollback'|null>(null);
  async function confirmAction(){if(confirm==='install')await updates.install();else if(confirm==='rollback')await updates.rollback();setConfirm(null);}
  const state=updates.state;
  const statusLabel=updates.mode==='native'?state.status.replaceAll('-',' '):(isVietnamese?'Máy chủ quản lý':'Host managed');
  return <section className="systemCard" data-testid="software-update">
    <div className="systemCardHeader"><span><Download/><span><strong>{isVietnamese?'Cập nhật phần mềm & firmware':'Software & firmware update'}</strong><small>{isVietnamese?'Gói cập nhật đã ký · cài đặt và rollback chỉ khi xe đang đỗ':'Signed-package workflow · install and rollback remain parked-only'}</small></span></span><b>{statusLabel}</b></div>
    <div className="updateVersionGrid"><div><small>{isVietnamese?'Phần mềm HMI':'HMI software'}</small><strong>v{state.currentVersion}</strong></div><div><small>{isVietnamese?'Firmware xe':'Vehicle firmware'}</small><strong>{state.firmwareVersion??(isVietnamese?'Máy chủ báo về':'Host reported')}</strong></div><div><small>{isVietnamese?'Bảo mật cập nhật':'Update security'}</small><strong>{state.available?state.available.signed?(isVietnamese?'Gói đã ký':'Signed package'):(isVietnamese?'Cần xác minh':'Verification required'):(isVietnamese?'Chưa có gói chờ':'No package staged')}</strong></div></div>
    {updates.mode==='host-managed'?<div className="systemNotice"><ShieldCheck/><span><strong>{isVietnamese?'Cập nhật do native vehicle host kiểm soát':'Updates are controlled by the native vehicle host'}</strong><small>{isVietnamese?'KINGMAST web UI không tải firmware từ URL tùy ý hoặc tự flash thiết bị. Native updater phải kiểm tra chữ ký gói, tương thích, nguồn điện ổn định, rollback slot và trạng thái xe đứng yên.':'KINGMAST web UI does not fetch arbitrary firmware URLs or flash devices. Package signature, compatibility, stable power, rollback slot and stationary state must be verified by the native updater.'}</small></span></div>:null}
    {state.available?<div className="updateAvailable"><Download/><span><strong>v{state.available.version} {isVietnamese?'khả dụng':'available'}</strong><small>{state.available.releaseNotes}{state.available.sizeMb?` · ${state.available.sizeMb} MB`:''}</small></span><b>{state.available.signed?(isVietnamese?'Đã xác minh':'Verified'):(isVietnamese?'Bị chặn':'Blocked')}</b></div>:null}
    {state.status==='downloading'||state.status==='installing'?<div className="updateProgress" aria-label={`${isVietnamese?'Tiến độ cập nhật':'Update progress'} ${Math.round(state.progressPct)}%`}><i style={{width:`${Math.max(0,Math.min(100,state.progressPct))}%`}}/><span>{Math.round(state.progressPct)}%</span></div>:null}
    {state.status==='reboot-required'?<div className="systemSuccess"><CheckCircle2/><span><strong>{isVietnamese?'Cần khởi động lại':'Restart required'}</strong><small>{isVietnamese?'Hoàn tất cập nhật qua máy chủ xe khi xe đang đỗ. KINGMAST web UI không tự khởi động lại bộ điều khiển xe.':'Complete the update through the vehicle host while parked. KINGMAST will not restart the vehicle controller from this web UI.'}</small></span></div>:null}
    <div className="systemButtonRow"><button type="button" disabled={updates.busy||updates.mode!=='native'} onClick={()=>void updates.check()}><RefreshCw/> {isVietnamese?'Kiểm tra cập nhật':'Check for updates'}</button>{state.available&&state.status==='available'?<button type="button" disabled={updates.busy||!state.available.signed} onClick={()=>void updates.download()}><Download/> {t('common.download')}</button>:null}{state.available&&state.status==='ready'?<button type="button" className="systemPrimary" disabled={updates.busy||!state.available.signed} onClick={()=>setConfirm('install')}><ShieldCheck/> {t('common.installSignedUpdate')}</button>:null}{state.rollbackAvailable?<button type="button" disabled={updates.busy} onClick={()=>setConfirm('rollback')}><RotateCcw/> {isVietnamese?'Quay lại bản trước':'Roll back'}</button>:null}</div>
    {confirm?<div className="maintenanceConfirm" role="group" aria-label={isVietnamese?'Xác nhận tác vụ cập nhật':'Confirm software update action'}><TriangleAlert/><span><strong>{confirm==='install'?(isVietnamese?'Cài bản cập nhật đã ký này?':'Install this signed update?'):(isVietnamese?'Quay lại rollback slot đã xác minh trước đó?':'Roll back to the previous verified slot?')}</strong><small>{confirm==='install'?(isVietnamese?'Giữ xe đỗ và nguồn điện ổn định. Native host vẫn chịu trách nhiệm xác minh chữ ký, tương thích và khôi phục khi cập nhật bị gián đoạn.':'Keep the vehicle parked with stable power. The native host remains responsible for signature and compatibility verification and interrupted-update recovery.'):(isVietnamese?'Rollback có thể thay đổi hành vi phần mềm. Chỉ dùng rollback slot đã xác minh và giữ xe đang đỗ.':'Rollback can change software behavior. Use only a previously verified rollback slot and keep the vehicle parked.')}</small></span><div><button type="button" onClick={()=>setConfirm(null)}>{t('common.cancel')}</button><button type="button" className="systemPrimary" onClick={()=>void confirmAction()}>{confirm==='install'?(isVietnamese?'Cài cập nhật':'Install update'):(isVietnamese?'Xác nhận rollback':'Confirm rollback')}</button></div></div>:null}
    {updates.error?<div className="systemError" role="status"><TriangleAlert/><span>{updates.error}</span></div>:null}
  </section>;
}
