export function round(value,digits=3){const p=10**digits;return Math.round(value*p)/p;}
function outcome(decision,reason,metrics={}){return{decision,reason,metrics};}
export function evaluateIndependentOracle(oracle){
  switch(oracle.kind){
    case 'closing-object':{if(oracle.visibility<0.45)return outcome('degrade','insufficient-visibility',{visibility:oracle.visibility});if(oracle.sensorAgreement===false)return outcome('degrade','sensor-disagreement');const closingSpeedMps=Math.max(0,oracle.egoSpeedMps-oracle.objectSpeedMps);const ttcS=closingSpeedMps>0?oracle.rangeM/closingSpeedMps:null;if(ttcS!==null&&ttcS<=3)return outcome('warn','closing-risk',{closingSpeedMps:round(closingSpeedMps),ttcS:round(ttcS)});return outcome('monitor','non-urgent-closing',{closingSpeedMps:round(closingSpeedMps),ttcS:ttcS===null?null:round(ttcS)});}
    case 'crossing-object':{if(oracle.visibility<0.45)return outcome('degrade','insufficient-visibility',{visibility:oracle.visibility});const egoArrivalS=oracle.egoSpeedMps>0?oracle.egoDistanceToConflictM/oracle.egoSpeedMps:Infinity;const actorArrivalS=oracle.actorSpeedMps>0?oracle.actorDistanceToConflictM/oracle.actorSpeedMps:Infinity;const arrivalDeltaS=Math.abs(egoArrivalS-actorArrivalS);if(Math.min(egoArrivalS,actorArrivalS)<=5&&arrivalDeltaS<=1.5)return outcome('warn','crossing-time-conflict',{egoArrivalS:round(egoArrivalS),actorArrivalS:round(actorArrivalS),arrivalDeltaS:round(arrivalDeltaS)});return outcome('monitor','crossing-no-immediate-conflict',{egoArrivalS:round(egoArrivalS),actorArrivalS:round(actorArrivalS),arrivalDeltaS:round(arrivalDeltaS)});}
    case 'sensor-health':{if(oracle.replay===true)return outcome('reject','replay-detected');if(Math.abs(oracle.clockSkewMs)>oracle.maxClockSkewMs)return outcome('reject','clock-skew',{clockSkewMs:oracle.clockSkewMs});if(oracle.occluded===true)return outcome('degrade','sensor-occluded');if(oracle.ageMs>oracle.maxAgeMs)return outcome('degrade','sensor-stale',{ageMs:oracle.ageMs,maxAgeMs:oracle.maxAgeMs});return outcome('monitor','sensor-fresh');}
    case 'lane':{if((oracle.markingsVisible!==true&&oracle.roadEdgeVisible!==true)||oracle.laneConfidence<0.5)return outcome('degrade','lane-boundary-unreliable',{laneConfidence:oracle.laneConfidence});if(oracle.turnSignal===true)return outcome('monitor','intentional-lane-change');if(oracle.timeToBoundaryS<=1.5)return outcome('warn','unintentional-lane-departure',{timeToBoundaryS:oracle.timeToBoundaryS});return outcome('monitor','lane-stable',{timeToBoundaryS:oracle.timeToBoundaryS});}
    case 'dms':{if(oracle.faceAvailable!==true||oracle.confidence<0.5)return outcome('degrade','driver-observation-unavailable',{confidence:oracle.confidence});if(oracle.temporalSpanS<3)return outcome('monitor','insufficient-temporal-evidence',{temporalSpanS:oracle.temporalSpanS});if(oracle.kss>=8)return outcome('warn','drowsiness-reference-threshold',{kss:oracle.kss});if(oracle.gazeAwayRatio>=0.6)return outcome('warn','sustained-driver-distraction',{gazeAwayRatio:oracle.gazeAwayRatio});return outcome('monitor','driver-state-nominal');}
    case 'speed':{const signUsable=Number.isFinite(oracle.signLimitKph)&&oracle.signConfidence>=0.7;const mapUsable=Number.isFinite(oracle.mapLimitKph);if(signUsable&&mapUsable&&oracle.signLimitKph!==oracle.mapLimitKph)return outcome('degrade','speed-source-disagreement',{mapLimitKph:oracle.mapLimitKph,signLimitKph:oracle.signLimitKph});const effectiveLimit=signUsable?oracle.signLimitKph:(mapUsable?oracle.mapLimitKph:null);if(!signUsable&&mapUsable&&Number.isFinite(oracle.signLimitKph))return outcome('monitor','low-confidence-sign-fallback',{effectiveLimitKph:effectiveLimit,signConfidence:oracle.signConfidence});if(effectiveLimit===null)return outcome('degrade','speed-limit-unavailable');if(oracle.egoSpeedKph>effectiveLimit+2)return outcome('warn','speed-limit-exceeded',{effectiveLimitKph:effectiveLimit,egoSpeedKph:oracle.egoSpeedKph});return outcome('monitor','speed-within-research-envelope',{effectiveLimitKph:effectiveLimit});}
    case 'blind-spot':{const inLateralZone=oracle.lateralAbsM>=1.2&&oracle.lateralAbsM<=3.8;const inLongitudinalZone=oracle.longitudinalM>=-6&&oracle.longitudinalM<=2;if(inLateralZone&&inLongitudinalZone)return outcome('warn','blind-spot-occupied',{closingSpeedMps:oracle.closingSpeedMps});return outcome('monitor','blind-spot-clear');}
    case 'surround':{const ready=oracle.cameraCount>=4&&oracle.calibratedCount===oracle.cameraCount&&oracle.synchronizedCount===oracle.cameraCount&&oracle.occludedCount===0&&oracle.maxReprojectionErrorPx<=3&&oracle.maxFrameSkewMs<=80;if(!ready)return outcome('degrade','surround-geometry-unreliable',{cameraCount:oracle.cameraCount,calibratedCount:oracle.calibratedCount,synchronizedCount:oracle.synchronizedCount,maxReprojectionErrorPx:oracle.maxReprojectionErrorPx,maxFrameSkewMs:oracle.maxFrameSkewMs});return outcome('monitor','surround-visualization-ready');}
    case 'provider':{if(oracle.trusted!==true)return outcome('reject','provider-untrusted');if(oracle.ageMs>oracle.maxAgeMs)return outcome('degrade','provider-stale',{ageMs:oracle.ageMs,maxAgeMs:oracle.maxAgeMs});if(oracle.approachingEmergency===true)return outcome('warn','verified-emergency-approaching');return outcome('monitor','provider-context-valid');}
    case 'update-integrity':{if(oracle.signatureValid!==true)return outcome('reject','update-signature-invalid');if(oracle.rollbackDetected===true)return outcome('reject','update-rollback-detected');return outcome('monitor','update-integrity-valid');}
    case 'warning-arbitration':{const hazards=Array.isArray(oracle.hazards)?oracle.hazards:[];const top=[...hazards].sort((a,b)=>b.priority-a.priority)[0]??null;if(top?.id==='collision')return outcome('warn','collision-critical-priority',{selected:top.id,suppressed:hazards.filter((item)=>item.id!==top.id).map((item)=>item.id)});return outcome('monitor','non-critical-context',{selected:top?.id??null});}
    case 'human-responsibility':{if(oracle.controlAuthority!=='none'||oracle.automatedActuationRequested===true)return outcome('reject','simulation-boundary-violation');if(oracle.driverResponsible===true)return outcome('monitor','warning-only-driver-responsibility');return outcome('degrade','driver-responsibility-ambiguous');}
    default:throw new Error(`unsupported independent oracle kind: ${String(oracle.kind)}`);
  }
}
