export const KINGMAST_ASSETS = {
  vehicle: {
    front: '/assets/kingmast/vehicle/kingmast-front-520.png',
  },
  icons: {
    home: '/assets/kingmast/icons/home.png',
    vehicle: '/assets/kingmast/icons/vehicle.png',
    navigation: '/assets/kingmast/icons/navigation.png',
    music: '/assets/kingmast/icons/music.png',
    phone: '/assets/kingmast/icons/phone.png',
    camera: '/assets/kingmast/icons/camera.png',
    cameraFilled: '/assets/kingmast/icons/camera-filled.png',
    settings: '/assets/kingmast/icons/settings.png',
    lane: '/assets/kingmast/icons/lane.png',
    radar: '/assets/kingmast/icons/radar.png',
    speed: '/assets/kingmast/icons/speed.png',
    map: '/assets/kingmast/icons/map.png',
    alert: '/assets/kingmast/icons/alert.png',
    battery: '/assets/kingmast/icons/battery.png',
    surround: '/assets/kingmast/icons/surround.png',
    steering: '/assets/kingmast/icons/steering.png',
    parking: '/assets/kingmast/icons/parking.png',
  },
  clusters: {
    vehicleExterior: '/assets/kingmast/ui/01-vehicle-exterior.png',
    keyIconsLine: '/assets/kingmast/ui/02-key-icons-line.png',
    keyIconsFilled: '/assets/kingmast/ui/03-key-icons-filled.png',
    vehicleStatus: '/assets/kingmast/ui/04-vehicle-status.png',
    speedHud: '/assets/kingmast/ui/05-speed-hud.png',
    alerts: '/assets/kingmast/ui/06-alert-banners.png',
    dmsSurround: '/assets/kingmast/ui/07-dms-surround.png',
    navClimateMedia: '/assets/kingmast/ui/08-navigation-climate-media.png',
    uiNotifications: '/assets/kingmast/ui/09-ui-notifications.png',
    additionalIcons: '/assets/kingmast/ui/10-additional-icons.png',
  },
} as const;
