'use client';

import { useCallback,useEffect,useMemo,useState } from 'react';
import type { EvProfile,GeoPoint,NavigationPlace,NavigationRoute,NavigationRouteOption,RoadContext,RouteIntelligence,VehiclePosition } from '@kingmast/contracts';

function apiBase(){return(process.env.NEXT_PUBLIC_KINGMAST_API_URL??'http://localhost:4000').replace(/\/$/,'');}
function simulatorFallback(vehicle:VehiclePosition):RoadContext{return{position:{lat:vehicle.lat,lng:vehicle.lng},speedLimit:{currentKmh:50,source:'simulator',confidence:.35,roadName:'Simulator road',conditional:null,observedAtMs:Date.now()},compliance:vehicle.speedKmh>53?'over-limit':vehicle.speedKmh>=47?'near-limit':'within-limit',cameras:[],fetchedAtMs:Date.now(),coverage:'unavailable',notes:['Simulated speed limit shown because the road-context API is unavailable.']};}

const ROUTE_CACHE_KEY='kingmast:v25:route';
const RECENTS_KEY='kingmast:v25:recent-places';
const EV_KEY='kingmast:v25:ev-profile';
const ROUTE_CACHE_MAX_AGE_MS=2*60*60*1000;
export const DEFAULT_EV_PROFILE:EvProfile={batteryPct:76,usableBatteryKwh:64,rangeKm:360,consumptionWhPerKm:165,reservePct:15};
interface StoredRoute{route:NavigationRoute;destination:GeoPoint;savedAtMs:number;}
function near(a:GeoPoint,b:GeoPoint){return Math.abs(a.lat-b.lat)<.001&&Math.abs(a.lng-b.lng)<.001;}
function clampEv(value:EvProfile):EvProfile{return{batteryPct:Math.max(0,Math.min(100,value.batteryPct)),usableBatteryKwh:Math.max(5,Math.min(250,value.usableBatteryKwh)),rangeKm:Math.max(0,Math.min(1500,value.rangeKm)),consumptionWhPerKm:Math.max(50,Math.min(600,value.consumptionWhPerKm)),reservePct:Math.max(0,Math.min(60,value.reservePct))};}

export interface RoadContextController{
  context:RoadContext|null;loading:boolean;error:string|null;
  route:NavigationRoute|null;routeLoading:boolean;routeFromCache:boolean;destination:GeoPoint|null;
  routeOptions:NavigationRouteOption[];selectedRouteId:string|null;selectRouteOption:(id:string)=>void;
  intelligence:RouteIntelligence|null;intelligenceLoading:boolean;intelligenceError:string|null;
  evProfile:EvProfile;setEvProfile:(profile:EvProfile)=>void;
  navigate:(destination:GeoPoint,place?:NavigationPlace)=>Promise<NavigationRoute|null>;reroute:()=>Promise<NavigationRoute|null>;clearRoute:()=>void;
  places:NavigationPlace[];recentPlaces:NavigationPlace[];searchLoading:boolean;searchPlaces:(query:string)=>Promise<NavigationPlace[]>;
}

export function useRoadContext(vehicle:VehiclePosition,radiusM:number):RoadContextController{
  const[context,setContext]=useState<RoadContext|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[route,setRoute]=useState<NavigationRoute|null>(null);const[routeLoading,setRouteLoading]=useState(false);const[routeFromCache,setRouteFromCache]=useState(false);const[destination,setDestination]=useState<GeoPoint|null>(null);const[routeOptions,setRouteOptions]=useState<NavigationRouteOption[]>([]);const[selectedRouteId,setSelectedRouteId]=useState<string|null>(null);const[intelligence,setIntelligence]=useState<RouteIntelligence|null>(null);const[intelligenceLoading,setIntelligenceLoading]=useState(false);const[intelligenceError,setIntelligenceError]=useState<string|null>(null);const[evProfile,setEvProfileState]=useState<EvProfile>(DEFAULT_EV_PROFILE);const[places,setPlaces]=useState<NavigationPlace[]>([]);const[recentPlaces,setRecentPlaces]=useState<NavigationPlace[]>([]);const[searchLoading,setSearchLoading]=useState(false);
  const roadKey=useMemo(()=>`${vehicle.lat.toFixed(4)}:${vehicle.lng.toFixed(4)}:${Math.round(vehicle.speedKmh/5)}`,[vehicle.lat,vehicle.lng,vehicle.speedKmh]);const intelligenceKey=useMemo(()=>`${route?.fetchedAtMs??0}:${vehicle.lat.toFixed(3)}:${vehicle.lng.toFixed(3)}`,[route?.fetchedAtMs,vehicle.lat,vehicle.lng]);

  useEffect(()=>{try{const raw=window.localStorage.getItem(ROUTE_CACHE_KEY);if(raw){const stored=JSON.parse(raw) as StoredRoute;if(stored?.route&&stored?.destination&&Date.now()-stored.savedAtMs<=ROUTE_CACHE_MAX_AGE_MS){setRoute(stored.route);setDestination(stored.destination);setRouteFromCache(true);}}const recentRaw=window.localStorage.getItem(RECENTS_KEY);if(recentRaw){const parsed=JSON.parse(recentRaw) as NavigationPlace[];if(Array.isArray(parsed))setRecentPlaces(parsed.slice(0,5));}const evRaw=window.localStorage.getItem(EV_KEY);if(evRaw)setEvProfileState(clampEv(JSON.parse(evRaw) as EvProfile));}catch{}},[]);
  useEffect(()=>{let cancelled=false;const load=async()=>{try{setError(null);const url=`${apiBase()}/v4/road-context?lat=${encodeURIComponent(vehicle.lat)}&lng=${encodeURIComponent(vehicle.lng)}&speedKmh=${encodeURIComponent(vehicle.speedKmh)}&radiusM=${radiusM}`;const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`road-context-${response.status}`);const value=await response.json() as RoadContext;if(!cancelled)setContext(value);}catch(errorValue){if(!cancelled){setError(errorValue instanceof Error?errorValue.message:'road-context-unavailable');setContext(vehicle.source==='simulator'?simulatorFallback(vehicle):null);}}finally{if(!cancelled)setLoading(false);}};void load();const timer=window.setInterval(()=>void load(),8_000);return()=>{cancelled=true;window.clearInterval(timer);};},[roadKey,radiusM,vehicle.lat,vehicle.lng,vehicle.source,vehicle.speedKmh]);
  useEffect(()=>{if(!route){setIntelligence(null);setIntelligenceError(null);return;}let cancelled=false;const load=async()=>{setIntelligenceLoading(true);try{const response=await fetch(`${apiBase()}/v5/navigation/intelligence`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({route,position:{lat:vehicle.lat,lng:vehicle.lng}})});if(!response.ok)throw new Error(`route-intelligence-${response.status}`);const value=await response.json() as RouteIntelligence;if(!cancelled){setIntelligence(value);setIntelligenceError(null);}}catch(errorValue){if(!cancelled)setIntelligenceError(errorValue instanceof Error?errorValue.message:'route-intelligence-unavailable');}finally{if(!cancelled)setIntelligenceLoading(false);}};void load();const timer=window.setInterval(()=>void load(),30_000);return()=>{cancelled=true;window.clearInterval(timer);};},[intelligenceKey,route,vehicle.lat,vehicle.lng]);

  const rememberPlace=useCallback((place:NavigationPlace)=>{setRecentPlaces((current)=>{const next=[place,...current.filter((item)=>item.id!==place.id)].slice(0,5);try{window.localStorage.setItem(RECENTS_KEY,JSON.stringify(next));}catch{}return next;});},[]);
  const setEvProfile=useCallback((profile:EvProfile)=>{const next=clampEv(profile);setEvProfileState(next);try{window.localStorage.setItem(EV_KEY,JSON.stringify(next));}catch{}},[]);
  const persistRoute=useCallback((value:NavigationRoute,destinationValue:GeoPoint)=>{try{window.localStorage.setItem(ROUTE_CACHE_KEY,JSON.stringify({route:value,destination:destinationValue,savedAtMs:Date.now()} satisfies StoredRoute));}catch{}},[]);
  const requestRoute=useCallback(async(destinationValue:GeoPoint,place?:NavigationPlace)=>{setRouteLoading(true);setError(null);try{let value:NavigationRoute|null=null;let options:NavigationRouteOption[]=[];const response=await fetch(`${apiBase()}/v5/navigation/alternatives`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({origin:{lat:vehicle.lat,lng:vehicle.lng},destination:destinationValue,evProfile})});if(response.ok){const payload=await response.json() as {routes?:NavigationRouteOption[]};options=payload.routes??[];const selected=options.find((item)=>item.recommended)??options[0];if(selected){value=selected.route;setSelectedRouteId(selected.id);setRouteOptions(options);}}if(!value){const fallback=await fetch(`${apiBase()}/v4/navigation/route`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({origin:{lat:vehicle.lat,lng:vehicle.lng},destination:destinationValue})});if(!fallback.ok)throw new Error(`navigation-${fallback.status}`);value=await fallback.json() as NavigationRoute;setRouteOptions([]);setSelectedRouteId(null);}setRoute(value);setDestination(destinationValue);setRouteFromCache(false);if(place)rememberPlace(place);persistRoute(value,destinationValue);return value;}catch(errorValue){setError(errorValue instanceof Error?errorValue.message:'navigation-unavailable');try{const raw=window.localStorage.getItem(ROUTE_CACHE_KEY);if(raw){const stored=JSON.parse(raw) as StoredRoute;if(Date.now()-stored.savedAtMs<=ROUTE_CACHE_MAX_AGE_MS&&near(stored.destination,destinationValue)){setRoute(stored.route);setDestination(stored.destination);setRouteFromCache(true);return stored.route;}}}catch{}return null;}finally{setRouteLoading(false);}},[evProfile,persistRoute,rememberPlace,vehicle.lat,vehicle.lng]);
  const navigate=useCallback((destinationValue:GeoPoint,place?:NavigationPlace)=>requestRoute(destinationValue,place),[requestRoute]);const reroute=useCallback(async()=>destination?requestRoute(destination):null,[destination,requestRoute]);
  const selectRouteOption=useCallback((id:string)=>{const option=routeOptions.find((item)=>item.id===id);if(!option||!destination)return;setSelectedRouteId(id);setRoute(option.route);setRouteFromCache(false);persistRoute(option.route,destination);},[destination,persistRoute,routeOptions]);
  const clearRoute=useCallback(()=>{setRoute(null);setDestination(null);setRouteFromCache(false);setRouteOptions([]);setSelectedRouteId(null);setIntelligence(null);try{window.localStorage.removeItem(ROUTE_CACHE_KEY);}catch{}},[]);
  const searchPlaces=useCallback(async(query:string)=>{const trimmed=query.trim();if(trimmed.length<2){setPlaces([]);return[];}setSearchLoading(true);setError(null);try{const url=`${apiBase()}/v4/navigation/search?q=${encodeURIComponent(trimmed)}&lat=${encodeURIComponent(vehicle.lat)}&lng=${encodeURIComponent(vehicle.lng)}`;const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`geocoding-${response.status}`);const value=await response.json() as {places?:NavigationPlace[]};const results=value.places??[];setPlaces(results);return results;}catch(errorValue){setError(errorValue instanceof Error?errorValue.message:'geocoding-unavailable');setPlaces([]);return[];}finally{setSearchLoading(false);}},[vehicle.lat,vehicle.lng]);
  return{context,loading,error,route,routeLoading,routeFromCache,destination,routeOptions,selectedRouteId,selectRouteOption,intelligence,intelligenceLoading,intelligenceError,evProfile,setEvProfile,navigate,reroute,clearRoute,places,recentPlaces,searchLoading,searchPlaces};
}
