import type { ChargingStation,DetectedObject,EvProfile,JunctionPreview,NavigationRouteOption,RouteIntelligence,Severity,SpeedZonePreview } from '@kingmast/contracts';

export interface SideAdvisory{severity:Severity;object:DetectedObject|null;}
export interface BlindSpotAdvisory{left:SideAdvisory;right:SideAdvisory;}
export interface CrossTrafficAdvisory{severity:Severity;side:'left'|'right'|null;object:DetectedObject|null;}
const SAFE:SideAdvisory={severity:'safe',object:null};
function stronger(a:Severity,b:Severity){const rank:Record<Severity,number>={safe:0,caution:1,critical:2};return rank[a]>=rank[b]?a:b;}
function objectSide(object:DetectedObject){if(object.zone==='left'||object.zone==='front-left')return'left' as const;if(object.zone==='right'||object.zone==='front-right')return'right' as const;const relative=((object.bearingDeg+540)%360)-180;return relative<0?'left' as const:'right' as const;}
function sideSeverity(object:DetectedObject):Severity{
  // Ordinary left/right detection is spatial context only. Keep the object visible
  // beside the ego vehicle, but do not promote it into a textual driver alert.
  if(object.severity==='critical'||object.distanceM<=4.5)return'critical';
  return'safe';
}

export function blindSpotAdvisory(objects:DetectedObject[]):BlindSpotAdvisory{let left:SideAdvisory={...SAFE},right:SideAdvisory={...SAFE};for(const object of objects){if(!['left','right','front-left','front-right'].includes(object.zone)||object.distanceM>14)continue;const side=objectSide(object),severity=sideSeverity(object);const current=side==='left'?left:right;if(current.object===null||severity==='critical'||object.distanceM<current.object.distanceM){const next={severity:stronger(current.severity,severity),object};if(side==='left')left=next;else right=next;}}return{left,right};}
export function crossTrafficAdvisory(objects:DetectedObject[],vehicleSpeedKmh:number):CrossTrafficAdvisory{if(vehicleSpeedKmh>10)return{severity:'safe',side:null,object:null};const candidates=objects.filter((object)=>object.zone==='rear'&&object.distanceM<=22&&object.relativeSpeedMps<-.8&&object.confidence>=.55).sort((a,b)=>a.distanceM-b.distanceM);const object=candidates[0]??null;if(!object)return{severity:'safe',side:null,object:null};return{severity:object.distanceM<=8||object.severity==='critical'?'critical':'caution',side:objectSide(object),object};}
export function nextSpeedZone(intelligence:RouteIntelligence|null,traveledM:number,currentLimit:number|null):{zone:SpeedZonePreview;distanceM:number}|null{if(!intelligence)return null;const candidate=intelligence.speedZones.map((zone)=>({zone,distanceM:zone.distanceAlongRouteM-traveledM})).filter((item)=>item.distanceM>30&&item.distanceM<=8_000&&(currentLimit===null||item.zone.limitKmh!==currentLimit)).sort((a,b)=>a.distanceM-b.distanceM)[0];return candidate??null;}
export function nextJunction(intelligence:RouteIntelligence|null,traveledM:number):{junction:JunctionPreview;distanceM:number}|null{if(!intelligence)return null;const candidate=intelligence.junctions.map((junction)=>({junction,distanceM:junction.distanceAlongRouteM-traveledM})).filter((item)=>item.distanceM>=0&&item.distanceM<=4_000).sort((a,b)=>a.distanceM-b.distanceM)[0];return candidate??null;}
export function chargingSuggestion(intelligence:RouteIntelligence|null,traveledM:number,routeOption:NavigationRouteOption|null,profile:EvProfile):{station:ChargingStation|null;arrivalBatteryPct:number;needsCharge:boolean}|null{if(!routeOption)return null;const arrivalBatteryPct=routeOption.estimatedArrivalBatteryPct;const needsCharge=arrivalBatteryPct<profile.reservePct;const station=intelligence?.chargingStations.map((value)=>({value,ahead:value.distanceAlongRouteM-traveledM})).filter((item)=>item.ahead>300&&item.value.detourDistanceM<=2_000).sort((a,b)=>a.ahead-b.ahead||a.value.detourDistanceM-b.value.detourDistanceM)[0]?.value??null;return{station,arrivalBatteryPct,needsCharge};}
export function advisorySeverity(base:Severity,blind:BlindSpotAdvisory,cross:CrossTrafficAdvisory,overLimit:boolean,energyLow:boolean):Severity{let value=base;if(blind.left.severity==='critical'||blind.right.severity==='critical'||cross.severity==='critical')value='critical';else if(value==='safe'&&(cross.severity==='caution'||overLimit||energyLow))value='caution';return value;}