[platformio]
include_dir = .

[env:esp32dev]
platform = espressif32@6.8.1
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@6.21.5
  mikalhart/TinyGPSPlus@1.0.3
build_flags =
  -Wall
  -Wextra
  -Werror=return-type
