import { afterEach,describe,expect,it } from 'vitest';
import type { ConnectedRoadAdvisory,ConnectedRoadProviderSnapshot,VehiclePosition } from '@kingmast/contracts';
import { clearConnectedRoadProviders,connectedRoadProviderStatus,getConnectedRoadContext,replaceConnectedRoadProvider,suppressConnectedRoadAdvisories } from './connected-road.js';

const vehicle:VehiclePosition={lat:21.0285,lng:105.8542,speedKmh:42,headingDeg:90,accuracyM:3,timestampMs:Date.now(),source:'simulator'};
afterEach(()=>clearConnectedRoadProviders());

describe('connected-road intelligence',()=>{
  it('keeps product development behavior warning-only while exposing simulator context',async()=>{const context=await getConnectedRoadContext({vehicle,route:null,collisionCritical:false});expect(context.coverage).toBe('simulator');expect(context.zones.some((zone)=>zone.kind==='school')).toBe(true);expect(context.zones.some((zone)=>zone.kind==='construction')).toBe(true);expect(context.laneTopology?.laneCount).toBe(3);expect(context.exits.length).toBeGreaterThan(0);});

  it('prioritizes an approaching emergency vehicle from a verified V2X snapshot',async()=>{const now=Date.now();const snapshot:ConnectedRoadProviderSnapshot={providerId:'test-v2x',timestampMs:now,security:{transport:'mtls',trustStatus:'verified',certificateExpiresAtMs:now+86_400_000,verifiedAtMs:now,detail:'test trust chain'},emergencyVehicles:[{id:'ambulance-1',kind:'ambulance',position:{lat:21.0285,lng:105.855},distanceM:180,bearingDeg:0,approach:'approaching',sirenDetected:true,confidence:.95,timestampMs:now,source:'v2x-provider'}],spat:[{intersectionId:'junction-1',name:'Test junction',position:{lat:21.0285,lng:105.856},approachHeadingDeg:90,movements:[{signalGroup:1,state:'stop-and-remain',minEndTimeMs:now+8_000,maxEndTimeMs:now+16_000,confidence:.9}],timestampMs:now,source:'v2x-provider'}]};replaceConnectedRoadProvider(snapshot);const context=await getConnectedRoadContext({vehicle:{...vehicle,source:'gnss'},route:null,collisionCritical:false});expect(context.coverage).toBe('provider-backed');expect(context.advisories[0]?.category).toBe('emergency-vehicle');expect(context.advisories[0]?.severity).toBe('critical');expect(connectedRoadProviderStatus(now)[0]?.liveV2xTrusted).toBe(true);});

  it('fails closed for expired live V2X state while exposing degraded provider health',async()=>{const now=Date.now();replaceConnectedRoadProvider({providerId:'expired-v2x',timestampMs:now,security:{transport:'mtls',trustStatus:'verified',certificateExpiresAtMs:now-1_000,verifiedAtMs:now-60_000,detail:'certificate expired'},emergencyVehicles:[{id:'ambulance-expired',kind:'ambulance',position:{lat:21.0285,lng:105.855},distanceM:120,bearingDeg:0,approach:'approaching',sirenDetected:true,confidence:.98,timestampMs:now,source:'v2x-provider'}],spat:[{intersectionId:'expired-signal',name:'Expired signal',position:{lat:21.0285,lng:105.856},approachHeadingDeg:90,movements:[{signalGroup:1,state:'stop-and-remain',minEndTimeMs:now+5_000,maxEndTimeMs:now+9_000,confidence:.99}],timestampMs:now,source:'v2x-provider'}]});const context=await getConnectedRoadContext({vehicle:{...vehicle,source:'gnss'},route:null,collisionCritical:false});expect(context.spat).toHaveLength(0);expect(context.emergencyVehicles).toHaveLength(0);expect(context.advisories.some((item)=>item.source==='v2x-provider')).toBe(false);expect(context.coverage).toBe('unavailable');const status=connectedRoadProviderStatus(now)[0];expect(status?.state).toBe('degraded');expect(status?.liveV2xTrusted).toBe(false);});

  it('suppresses connected-road notices while a collision-critical warning owns attention',()=>{const items:ConnectedRoadAdvisory[]=[{id:'school',category:'school-zone',severity:'caution',priority:72,title:'School zone',message:'Ahead',distanceM:200,dedupeKey:'zone:school',suppressible:true,expiresAtMs:null,source:'authorized-provider'},{id:'exit',category:'highway-exit',severity:'safe',priority:30,title:'Exit',message:'Ahead',distanceM:800,dedupeKey:'exit:1',suppressible:true,expiresAtMs:null,source:'authorized-provider'}];const result=suppressConnectedRoadAdvisories(items,true);expect(result.advisories).toHaveLength(0);expect(result.suppressionReason).toBe('collision-critical-warning-active');expect(result.suppressedCount).toBe(2);});

  it('deduplicates advisories and suppresses generic weather when a specific road hazard exists',()=>{const items:ConnectedRoadAdvisory[]=[{id:'weather',category:'weather',severity:'caution',priority:60,title:'Rain',message:'Wet road',distanceM:null,dedupeKey:'weather:context',suppressible:true,expiresAtMs:null,source:'authorized-provider'},{id:'flood',category:'road-hazard',severity:'critical',priority:84,title:'Flooding',message:'Ahead',distanceM:120,dedupeKey:'hazard:flood',suppressible:true,expiresAtMs:null,source:'authorized-provider'},{id:'flood-duplicate',category:'road-hazard',severity:'caution',priority:70,title:'Flooding',message:'Duplicate',distanceM:125,dedupeKey:'hazard:flood',suppressible:true,expiresAtMs:null,source:'authorized-provider'}];const result=suppressConnectedRoadAdvisories(items,false);expect(result.advisories.map((item)=>item.id)).toEqual(['flood']);expect(result.suppressedCount).toBe(2);});
});