import type { EvProfile,GeoPoint,NavigationPlace,NavigationRoute,NavigationRouteOption,NavigationStep } from '@kingmast/contracts';

const ROUTING_BASE_URL=(process.env.ROUTING_BASE_URL??'https://router.project-osrm.org').replace(/\/$/,'');
const GEOCODING_BASE_URL=(process.env.GEOCODING_BASE_URL??'https://nominatim.openstreetmap.org').replace(/\/$/,'');
const DEFAULT_EV:EvProfile={batteryPct:76,usableBatteryKwh:64,rangeKm:360,consumptionWhPerKm:165,reservePct:15};

interface OsrmStep { distance?:number; duration?:number; name?:string; maneuver?:{type?:string;modifier?:string;location?:[number,number]}; }
interface OsrmRoute { distance?:number; duration?:number; geometry?:{coordinates?:Array<[number,number]>}; legs?:Array<{steps?:OsrmStep[]}>; }
interface OsrmResponse { code?:string; routes?:OsrmRoute[]; }
interface GeocoderItem { place_id?:number|string; lat?:string; lon?:string; display_name?:string; name?:string; type?:string; }

function instruction(step:OsrmStep){const type=(step.maneuver?.type??'continue').replace(/_/g,' ');const modifier=step.maneuver?.modifier?.replace(/_/g,' ');const road=step.name?.trim();return`${type}${modifier?` ${modifier}`:''}${road?` onto ${road}`:''}`.replace(/^./,(letter)=>letter.toUpperCase());}
function routeFromOsrm(raw:OsrmRoute,origin:GeoPoint,destination:GeoPoint):NavigationRoute{const geometry=(raw.geometry?.coordinates??[]).slice(0,1800).map(([lng,lat])=>({lat,lng}));const steps:NavigationStep[]=(raw.legs??[]).flatMap((leg)=>leg.steps??[]).slice(0,120).map((step)=>{const location=step.maneuver?.location??[origin.lng,origin.lat];return{instruction:instruction(step),distanceM:step.distance??0,durationS:step.duration??0,location:{lng:location[0],lat:location[1]},roadName:step.name?.trim()||null};});return{provider:'osrm',origin,destination,distanceM:raw.distance??0,durationS:raw.duration??0,geometry,steps,fetchedAtMs:Date.now()};}
export function estimateRouteEnergyKwh(distanceM:number,profile:EvProfile=DEFAULT_EV){return Math.max(0,distanceM)*profile.consumptionWhPerKm/1_000_000;}
function routeOption(route:NavigationRoute,index:number,profile:EvProfile,minDuration:number,minEnergy:number):NavigationRouteOption{const energy=estimateRouteEnergyKwh(route.distanceM,profile);const usedPct=profile.usableBatteryKwh>0?energy/profile.usableBatteryKwh*100:100;const arrival=Math.max(0,profile.batteryPct-usedPct);const reserveMargin=arrival-profile.reservePct;const durationPenalty=minDuration>0?(route.durationS-minDuration)/minDuration:0;const energyPenalty=minEnergy>0?(energy-minEnergy)/minEnergy:0;const reservePenalty=reserveMargin<0?Math.abs(reserveMargin)/100:0;const score=durationPenalty*.52+energyPenalty*.33+reservePenalty*.9;return{id:`route-${index}-${Math.round(route.distanceM)}-${Math.round(route.durationS)}`,label:index===0?'Fastest':`Alternative ${index}`,route,estimatedEnergyKwh:energy,estimatedArrivalBatteryPct:arrival,reserveMarginPct:reserveMargin,recommended:false,score};}

async function requestOsrm(origin:GeoPoint,destination:GeoPoint,alternatives:boolean){const url=`${ROUTING_BASE_URL}/route/v1/driving/${origin.lng},${origin.lat};${destination.lng},${destination.lat}?overview=full&geometries=geojson&steps=true&alternatives=${alternatives?'true':'false'}`;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),5_500);try{const response=await fetch(url,{signal:controller.signal,headers:{'user-agent':'KINGMAST-navigation-research/2.5'}});if(!response.ok)throw new Error(`routing-http-${response.status}`);const raw=await response.json() as OsrmResponse;if(raw.code!=='Ok'||!raw.routes?.length)throw new Error('route-unavailable');return raw.routes;}finally{clearTimeout(timer);}}

export async function calculateNavigationAlternatives(origin:GeoPoint,destination:GeoPoint,profile:EvProfile=DEFAULT_EV):Promise<NavigationRouteOption[]>{const rawRoutes=await requestOsrm(origin,destination,true);const routes=rawRoutes.slice(0,3).map((route)=>routeFromOsrm(route,origin,destination));const minDuration=Math.min(...routes.map((route)=>route.durationS||Number.POSITIVE_INFINITY));const energies=routes.map((route)=>estimateRouteEnergyKwh(route.distanceM,profile));const minEnergy=Math.min(...energies);const options=routes.map((route,index)=>routeOption(route,index,profile,minDuration,minEnergy)).sort((a,b)=>a.score-b.score);if(options[0])options[0]={...options[0],recommended:true,label:options[0].label==='Fastest'?'Recommended':options[0].label};return options;}
export async function calculateNavigationRoute(origin:GeoPoint,destination:GeoPoint):Promise<NavigationRoute>{const routes=await calculateNavigationAlternatives(origin,destination,DEFAULT_EV);if(!routes[0])throw new Error('route-unavailable');return routes[0].route;}

export function parseNavigationPlaces(raw:unknown):NavigationPlace[]{if(!Array.isArray(raw))return[];return raw.slice(0,6).map((value,index)=>{if(!value||typeof value!=='object')return null;const item=value as GeocoderItem;const lat=Number(item.lat),lng=Number(item.lon);if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<-90||lat>90||lng<-180||lng>180)return null;const display=(item.display_name??'').trim();const name=(item.name??display.split(',')[0]??'Destination').trim()||'Destination';const subtitle=display&&display!==name?display:null;return{id:String(item.place_id??`${lat}:${lng}:${index}`),name,subtitle,position:{lat,lng},source:'geocoder' as const};}).filter((value):value is NavigationPlace=>value!==null);}
export async function searchNavigationPlaces(query:string,near?:GeoPoint):Promise<NavigationPlace[]>{const trimmed=query.trim();if(trimmed.length<2)return[];const url=new URL(`${GEOCODING_BASE_URL}/search`);url.searchParams.set('format','jsonv2');url.searchParams.set('q',trimmed);url.searchParams.set('limit','6');url.searchParams.set('addressdetails','0');if(near){const d=.28;url.searchParams.set('viewbox',`${near.lng-d},${near.lat+d},${near.lng+d},${near.lat-d}`);url.searchParams.set('bounded','0');}const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),4_500);try{const response=await fetch(url,{signal:controller.signal,headers:{'user-agent':'KINGMAST-navigation-research/2.5'}});if(!response.ok)throw new Error(`geocoding-http-${response.status}`);return parseNavigationPlaces(await response.json());}finally{clearTimeout(timer);}}
