import type { EvProfile,GeoPoint,NavigationPlace,NavigationRoute,NavigationRouteOption,NavigationStep } from '@kingmast/contracts';
import { compactNavigationSteps,compactRouteGeometry } from './route-compaction.js';

const ROUTING_BASE_URL=(process.env.ROUTING_BASE_URL??'https://router.project-osrm.org').replace(/\/$/,'');
const GEOCODING_BASE_URL=(process.env.GEOCODING_BASE_URL??'https://nominatim.openstreetmap.org').replace(/\/$/,'');
const GOOGLE_ROUTES_URL=(process.env.GOOGLE_ROUTES_BASE_URL??'https://routes.googleapis.com').replace(/\/$/,'');
const MAPBOX_DIRECTIONS_URL=(process.env.MAPBOX_DIRECTIONS_BASE_URL??'https://api.mapbox.com').replace(/\/$/,'');
const DEFAULT_EV:EvProfile={batteryPct:76,usableBatteryKwh:64,rangeKm:360,consumptionWhPerKm:165,reservePct:15};
type RoutingBackend='google'|'mapbox'|'osrm';

interface OsrmStep { distance?:number; duration?:number; name?:string; maneuver?:{type?:string;modifier?:string;location?:[number,number]}; }
interface OsrmRoute { distance?:number; duration?:number; geometry?:{coordinates?:Array<[number,number]>}; legs?:Array<{steps?:OsrmStep[]}>; }
interface OsrmResponse { code?:string; routes?:OsrmRoute[]; }
interface MapboxStep { distance?:number; duration?:number; name?:string; maneuver?:{instruction?:string;location?:[number,number]}; }
interface MapboxRoute { distance?:number; duration?:number; duration_typical?:number; geometry?:{type?:string;coordinates?:Array<[number,number]>}; legs?:Array<{steps?:MapboxStep[]}>; }
interface MapboxResponse { code?:string; routes?:MapboxRoute[]; }
interface GoogleStep { distanceMeters?:number; staticDuration?:string; startLocation?:{latLng?:{latitude?:number;longitude?:number}}; navigationInstruction?:{instructions?:string}; }
interface GoogleRoute { distanceMeters?:number; duration?:string; staticDuration?:string; polyline?:{geoJsonLinestring?:{type?:string;coordinates?:unknown}}; legs?:Array<{steps?:GoogleStep[]}>; }
interface GoogleResponse { routes?:GoogleRoute[]; }
interface GeocoderItem { place_id?:number|string; lat?:string; lon?:string; display_name?:string; name?:string; type?:string; }

function instruction(step:OsrmStep){const type=(step.maneuver?.type??'continue').replace(/_/g,' ');const modifier=step.maneuver?.modifier?.replace(/_/g,' ');const road=step.name?.trim();return`${type}${modifier?` ${modifier}`:''}${road?` onto ${road}`:''}`.replace(/^./,(letter)=>letter.toUpperCase());}
function durationSeconds(value:unknown){if(typeof value!=='string'||!/^\d+(?:\.\d+)?s$/.test(value))return 0;const parsed=Number(value.slice(0,-1));return Number.isFinite(parsed)?Math.max(0,parsed):0;}
function coordinateLine(value:unknown):GeoPoint[]{if(!Array.isArray(value))return[];const points=value.map((point)=>Array.isArray(point)&&point.length>=2?{lng:Number(point[0]),lat:Number(point[1])}:null).filter((point):point is GeoPoint=>Boolean(point&&Number.isFinite(point.lat)&&Number.isFinite(point.lng)&&point.lat>=-90&&point.lat<=90&&point.lng>=-180&&point.lng<=180));return points.length>1?compactRouteGeometry(points,1800):points;}
function fallbackStep(origin:GeoPoint,distanceM:number,durationS:number):NavigationStep{return{instruction:'Follow the highlighted route',distanceM,durationS,location:origin,roadName:null};}
function routeFromOsrm(raw:OsrmRoute,origin:GeoPoint,destination:GeoPoint):NavigationRoute{const geometry=coordinateLine(raw.geometry?.coordinates);const mappedSteps:NavigationStep[]=(raw.legs??[]).flatMap((leg)=>leg.steps??[]).map((step)=>{const location=step.maneuver?.location??[origin.lng,origin.lat];return{instruction:instruction(step),distanceM:step.distance??0,durationS:step.duration??0,location:{lng:location[0],lat:location[1]},roadName:step.name?.trim()||null};});const steps= mappedSteps.length>1?compactNavigationSteps(mappedSteps,120):mappedSteps;const distanceM=raw.distance??0,durationS=raw.duration??0;return{provider:'osrm',origin,destination,distanceM,durationS,geometry:geometry.length>=2?geometry:[origin,destination],steps:steps.length?steps:[fallbackStep(origin,distanceM,durationS)],fetchedAtMs:Date.now(),traffic:{aware:false,source:'none',delayS:null,observedAtMs:null}};}
function routeFromMapbox(raw:MapboxRoute,origin:GeoPoint,destination:GeoPoint):NavigationRoute{const distanceM=Math.max(0,raw.distance??0),durationS=Math.max(0,raw.duration??0),typical=Math.max(0,raw.duration_typical??0);const geometry=coordinateLine(raw.geometry?.coordinates);const mappedSteps:NavigationStep[]=(raw.legs??[]).flatMap((leg)=>leg.steps??[]).map((step)=>{const location=step.maneuver?.location??[origin.lng,origin.lat];return{instruction:(step.maneuver?.instruction??'Continue').trim().slice(0,500),distanceM:Math.max(0,step.distance??0),durationS:Math.max(0,step.duration??0),location:{lng:location[0],lat:location[1]},roadName:step.name?.trim()||null};});const steps=mappedSteps.length>1?compactNavigationSteps(mappedSteps,120):mappedSteps;return{provider:'mapbox',origin,destination,distanceM,durationS,geometry:geometry.length>=2?geometry:[origin,destination],steps:steps.length?steps:[fallbackStep(origin,distanceM,durationS)],fetchedAtMs:Date.now(),traffic:{aware:true,source:'mapbox-live',delayS:typical>0?Math.max(0,durationS-typical):null,observedAtMs:Date.now()}};}
function routeFromGoogle(raw:GoogleRoute,origin:GeoPoint,destination:GeoPoint):NavigationRoute{const distanceM=Math.max(0,raw.distanceMeters??0),durationS=durationSeconds(raw.duration),staticDuration=durationSeconds(raw.staticDuration);const geometry=coordinateLine(raw.polyline?.geoJsonLinestring?.coordinates);const mappedSteps:NavigationStep[]=(raw.legs??[]).flatMap((leg)=>leg.steps??[]).map((step)=>{const lat=step.startLocation?.latLng?.latitude,lng=step.startLocation?.latLng?.longitude;const location=Number.isFinite(lat)&&Number.isFinite(lng)?{lat:lat!,lng:lng!}:origin;return{instruction:(step.navigationInstruction?.instructions??'Continue').trim().slice(0,500),distanceM:Math.max(0,step.distanceMeters??0),durationS:durationSeconds(step.staticDuration),location,roadName:null};});const steps=mappedSteps.length>1?compactNavigationSteps(mappedSteps,120):mappedSteps;return{provider:'google-routes',origin,destination,distanceM,durationS,geometry:geometry.length>=2?geometry:[origin,destination],steps:steps.length?steps:[fallbackStep(origin,distanceM,durationS)],fetchedAtMs:Date.now(),traffic:{aware:true,source:'google-live',delayS:staticDuration>0?Math.max(0,durationS-staticDuration):null,observedAtMs:Date.now()}};}

export function estimateRouteEnergyKwh(distanceM:number,profile:EvProfile=DEFAULT_EV){return Math.max(0,distanceM)*profile.consumptionWhPerKm/1_000_000;}
function routeOption(route:NavigationRoute,index:number,profile:EvProfile,minDuration:number,minEnergy:number):NavigationRouteOption{const energy=estimateRouteEnergyKwh(route.distanceM,profile);const usedPct=profile.usableBatteryKwh>0?energy/profile.usableBatteryKwh*100:100;const arrival=Math.max(0,profile.batteryPct-usedPct);const reserveMargin=arrival-profile.reservePct;const durationPenalty=minDuration>0?(route.durationS-minDuration)/minDuration:0;const energyPenalty=minEnergy>0?(energy-minEnergy)/minEnergy:0;const reservePenalty=reserveMargin<0?Math.abs(reserveMargin)/100:0;const score=durationPenalty*.52+energyPenalty*.33+reservePenalty*.9;return{id:`route-${route.provider}-${index}-${Math.round(route.distanceM)}-${Math.round(route.durationS)}`,label:index===0?'Fastest':`Alternative ${index}`,route,estimatedEnergyKwh:energy,estimatedArrivalBatteryPct:arrival,reserveMarginPct:reserveMargin,recommended:false,score};}
function routingOrder():RoutingBackend[]{const configured=(process.env.KINGMAST_TRAFFIC_ROUTING_PROVIDER??'auto').trim().toLowerCase();const google=Boolean(process.env.GOOGLE_ROUTES_API_KEY?.trim()),mapbox=Boolean(process.env.MAPBOX_ACCESS_TOKEN?.trim());if(configured==='google')return google?['google','osrm']:['osrm'];if(configured==='mapbox')return mapbox?['mapbox','osrm']:['osrm'];if(configured==='osrm')return['osrm'];return[...(google?['google' as const]:[]),...(mapbox?['mapbox' as const]:[]),'osrm'];}

async function requestOsrm(origin:GeoPoint,destination:GeoPoint,alternatives:boolean){const url=`${ROUTING_BASE_URL}/route/v1/driving/${origin.lng},${origin.lat};${destination.lng},${destination.lat}?overview=full&geometries=geojson&steps=true&alternatives=${alternatives?'true':'false'}`;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),5_500);try{const response=await fetch(url,{signal:controller.signal,headers:{'user-agent':'KINGMAST-navigation-research/0.0.8'}});if(!response.ok)throw new Error(`routing-http-${response.status}`);const raw=await response.json() as OsrmResponse;if(raw.code!=='Ok'||!raw.routes?.length)throw new Error('route-unavailable');return raw.routes.slice(0,3).map((route)=>routeFromOsrm(route,origin,destination));}finally{clearTimeout(timer);}}
async function requestMapbox(origin:GeoPoint,destination:GeoPoint){const token=(process.env.MAPBOX_ACCESS_TOKEN??'').trim();if(!token)throw new Error('mapbox-not-configured');const url=new URL(`${MAPBOX_DIRECTIONS_URL}/directions/v5/mapbox/driving-traffic/${origin.lng},${origin.lat};${destination.lng},${destination.lat}`);url.searchParams.set('access_token',token);url.searchParams.set('alternatives','true');url.searchParams.set('overview','full');url.searchParams.set('geometries','geojson');url.searchParams.set('steps','true');url.searchParams.set('language','vi');url.searchParams.set('annotations','congestion_numeric,closure');const response=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(5_500),headers:{'user-agent':'KINGMAST-navigation-research/0.0.8'}});if(!response.ok)throw new Error(`mapbox-routing-${response.status}`);const raw=await response.json() as MapboxResponse;if(raw.code!=='Ok'||!raw.routes?.length)throw new Error('mapbox-route-unavailable');return raw.routes.slice(0,3).map((route)=>routeFromMapbox(route,origin,destination));}
async function requestGoogle(origin:GeoPoint,destination:GeoPoint){const key=(process.env.GOOGLE_ROUTES_API_KEY??'').trim();if(!key)throw new Error('google-routes-not-configured');const response=await fetch(`${GOOGLE_ROUTES_URL}/directions/v2:computeRoutes`,{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':key,'x-goog-fieldmask':'routes.distanceMeters,routes.duration,routes.staticDuration,routes.polyline.geoJsonLinestring,routes.legs.steps.distanceMeters,routes.legs.steps.staticDuration,routes.legs.steps.startLocation,routes.legs.steps.navigationInstruction.instructions'},body:JSON.stringify({origin:{location:{latLng:{latitude:origin.lat,longitude:origin.lng}}},destination:{location:{latLng:{latitude:destination.lat,longitude:destination.lng}}},travelMode:'DRIVE',routingPreference:'TRAFFIC_AWARE_OPTIMAL',computeAlternativeRoutes:true,polylineQuality:'OVERVIEW',polylineEncoding:'GEO_JSON_LINESTRING'}),cache:'no-store',signal:AbortSignal.timeout(5_500)});if(!response.ok)throw new Error(`google-routing-${response.status}`);const raw=await response.json() as GoogleResponse;if(!raw.routes?.length)throw new Error('google-route-unavailable');return raw.routes.slice(0,3).map((route)=>routeFromGoogle(route,origin,destination));}
async function requestPreferredRoutes(origin:GeoPoint,destination:GeoPoint){let lastError:unknown=null;for(const backend of routingOrder()){try{if(backend==='google')return await requestGoogle(origin,destination);if(backend==='mapbox')return await requestMapbox(origin,destination);return await requestOsrm(origin,destination,true);}catch(error){lastError=error;}}throw lastError instanceof Error?lastError:new Error('route-unavailable');}

export async function calculateNavigationAlternatives(origin:GeoPoint,destination:GeoPoint,profile:EvProfile=DEFAULT_EV):Promise<NavigationRouteOption[]>{const routes=await requestPreferredRoutes(origin,destination);const minDuration=Math.min(...routes.map((route)=>route.durationS||Number.POSITIVE_INFINITY));const energies=routes.map((route)=>estimateRouteEnergyKwh(route.distanceM,profile));const minEnergy=Math.min(...energies);const options=routes.map((route,index)=>routeOption(route,index,profile,minDuration,minEnergy)).sort((a,b)=>a.score-b.score);if(options[0])options[0]={...options[0],recommended:true,label:options[0].route.traffic?.aware?'Recommended · live traffic':'Recommended · routing data'};return options;}
export async function calculateNavigationRoute(origin:GeoPoint,destination:GeoPoint):Promise<NavigationRoute>{const routes=await calculateNavigationAlternatives(origin,destination,DEFAULT_EV);if(!routes[0])throw new Error('route-unavailable');return routes[0].route;}

export function parseNavigationPlaces(raw:unknown):NavigationPlace[]{if(!Array.isArray(raw))return[];return raw.slice(0,6).map((value,index)=>{if(!value||typeof value!=='object')return null;const item=value as GeocoderItem;const lat=Number(item.lat),lng=Number(item.lon);if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<-90||lat>90||lng<-180||lng>180)return null;const display=(item.display_name??'').trim();const name=(item.name??display.split(',')[0]??'Destination').trim()||'Destination';const subtitle=display&&display!==name?display:null;return{id:String(item.place_id??`${lat}:${lng}:${index}`),name,subtitle,position:{lat,lng},source:'geocoder' as const};}).filter((value):value is NavigationPlace=>value!==null);}
export async function searchNavigationPlaces(query:string,near?:GeoPoint):Promise<NavigationPlace[]>{const trimmed=query.trim();if(trimmed.length<2)return[];const url=new URL(`${GEOCODING_BASE_URL}/search`);url.searchParams.set('format','jsonv2');url.searchParams.set('q',trimmed);url.searchParams.set('limit','6');url.searchParams.set('addressdetails','0');if(near){const d=.28;url.searchParams.set('viewbox',`${near.lng-d},${near.lat+d},${near.lng+d},${near.lat-d}`);url.searchParams.set('bounded','0');}const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),4_500);try{const response=await fetch(url,{signal:controller.signal,headers:{'user-agent':'KINGMAST-navigation-research/0.0.8'}});if(!response.ok)throw new Error(`geocoding-http-${response.status}`);return parseNavigationPlaces(await response.json());}finally{clearTimeout(timer);}}
