import { timingSafeEqual } from 'node:crypto';
import type { FastifyPluginAsync,FastifyReply,FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { ConnectedRoadProviderSnapshot,EvProfile,NavigationRoute,SpeedSignObservation,TrafficCamera,VehiclePosition } from '@kingmast/contracts';
import { calculateNavigationAlternatives,calculateNavigationRoute,searchNavigationPlaces } from './navigation.js';
import { configuredCameraProviderCount,getRoadContext,replaceRuntimeCameraProvider,setLatestSpeedSign } from './road-context.js';
import { getRouteIntelligence } from './route-intelligence.js';
import { configuredConnectedRoadProviderCount,getConnectedRoadContext,replaceConnectedRoadProvider } from './connected-road.js';

const GeoPoint=z.object({lat:z.number().min(-90).max(90),lng:z.number().min(-180).max(180)});
const RoadQuery=z.object({lat:z.coerce.number().min(-90).max(90),lng:z.coerce.number().min(-180).max(180),speedKmh:z.coerce.number().min(0).max(350).default(0),radiusM:z.coerce.number().int().min(100).max(5000).default(1500)});
const RouteBody=z.object({origin:GeoPoint,destination:GeoPoint});
const SearchQuery=z.object({q:z.string().trim().min(2).max(120),lat:z.coerce.number().min(-90).max(90).optional(),lng:z.coerce.number().min(-180).max(180).optional()});
const EvProfileSchema=z.object({batteryPct:z.number().min(0).max(100),usableBatteryKwh:z.number().min(5).max(250),rangeKm:z.number().min(0).max(1500),consumptionWhPerKm:z.number().min(50).max(600),reservePct:z.number().min(0).max(60)});
const AlternativesBody=RouteBody.extend({evProfile:EvProfileSchema.optional()});
const NavigationStep=z.object({instruction:z.string(),distanceM:z.number(),durationS:z.number(),location:GeoPoint,roadName:z.string().nullable()});
const NavigationRouteSchema=z.object({provider:z.literal('osrm'),origin:GeoPoint,destination:GeoPoint,distanceM:z.number().nonnegative(),durationS:z.number().nonnegative(),geometry:z.array(GeoPoint).min(2).max(1800),steps:z.array(NavigationStep).max(120),fetchedAtMs:z.number().int().positive()});
const IntelligenceBody=z.object({route:NavigationRouteSchema,position:GeoPoint});
const SpeedSignBody=z.object({cameraId:z.string().min(1).max(96),speedLimitKmh:z.number().int().min(5).max(180),confidence:z.number().min(0).max(1),bearingDeg:z.number().min(-180).max(180),timestampMs:z.number().int().positive()});
const CameraKind=z.enum(['traffic-monitoring','speed-enforcement','red-light','average-speed','unknown']);
const RuntimeCamera=z.object({id:z.string().min(1).max(160),position:GeoPoint,kind:CameraKind,operator:z.string().max(160).nullable().optional(),ref:z.string().max(160).nullable().optional(),directionDeg:z.number().min(0).max(360).nullable().optional(),speedLimitKmh:z.number().min(1).max(250).nullable().optional(),viewerUrl:z.string().url().nullable().optional(),publicData:z.boolean().default(false)});
const RuntimeCameraBody=z.object({providerId:z.string().min(2).max(96),cameras:z.array(RuntimeCamera).max(5000)});

const ConnectedSource=z.enum(['v2x-provider','authorized-provider','public-map','vehicle-sensor','simulator']);
const SpatMovement=z.object({signalGroup:z.number().int().min(0).max(255),state:z.enum(['stop-and-remain','protected-movement-allowed','permissive-movement-allowed','protected-clearance','permissive-clearance','dark','unknown']),minEndTimeMs:z.number().int().positive().nullable(),maxEndTimeMs:z.number().int().positive().nullable(),confidence:z.number().min(0).max(1)});
const SpatIntersection=z.object({intersectionId:z.string().min(1).max(160),name:z.string().max(200).nullable(),position:GeoPoint,approachHeadingDeg:z.number().min(0).max(360).nullable(),movements:z.array(SpatMovement).max(32),timestampMs:z.number().int().positive(),source:ConnectedSource});
const RoadZone=z.object({id:z.string().min(1).max(160),kind:z.enum(['school','construction']),name:z.string().max(200).nullable(),position:GeoPoint,radiusM:z.number().min(5).max(10_000),active:z.boolean(),advisorySpeedKmh:z.number().min(5).max(180).nullable(),routeDistanceM:z.number().min(-10_000).max(100_000).nullable(),startsAtMs:z.number().int().positive().nullable(),endsAtMs:z.number().int().positive().nullable(),source:ConnectedSource,confidence:z.number().min(0).max(1)});
const RoadHazard=z.object({id:z.string().min(1).max(160),kind:z.enum(['pothole','flooding','debris','low-visibility','slippery','crosswind','roadwork','unknown']),title:z.string().min(1).max(200),position:GeoPoint,distanceM:z.number().min(0).max(100_000).nullable(),severity:z.enum(['caution','critical']),confidence:z.number().min(0).max(1),expiresAtMs:z.number().int().positive().nullable(),source:ConnectedSource});
const Weather=z.object({condition:z.enum(['clear','rain','heavy-rain','fog','storm','snow','unknown']),temperatureC:z.number().min(-80).max(80).nullable(),precipitationMmH:z.number().min(0).max(500).nullable(),visibilityM:z.number().min(0).max(100_000).nullable(),windKmh:z.number().min(0).max(400).nullable(),roadSurface:z.enum(['dry','wet','standing-water','icy','snow-covered','unknown']),hazards:z.array(RoadHazard).max(64),timestampMs:z.number().int().positive(),source:ConnectedSource,confidence:z.number().min(0).max(1)});
const EmergencyVehicle=z.object({id:z.string().min(1).max(160),kind:z.enum(['ambulance','fire','police','rescue','unknown']),position:GeoPoint,distanceM:z.number().min(0).max(100_000).nullable(),bearingDeg:z.number().min(-180).max(360).nullable(),approach:z.enum(['approaching','receding','stationary','unknown']),sirenDetected:z.boolean(),confidence:z.number().min(0).max(1),timestampMs:z.number().int().positive(),source:ConnectedSource});
const LaneManeuver=z.enum(['straight','left','right','uturn','merge-left','merge-right','exit','unknown']);
const LaneDescriptor=z.object({index:z.number().int().min(0).max(15),maneuvers:z.array(LaneManeuver).max(8),preferred:z.boolean(),exitOnly:z.boolean(),destination:z.string().max(200).nullable()});
const LaneTopology=z.object({roadName:z.string().max(200).nullable(),roadRef:z.string().max(80).nullable(),laneCount:z.number().int().min(1).max(16),currentLaneIndex:z.number().int().min(0).max(15).nullable(),lanes:z.array(LaneDescriptor).max(16),drivingSide:z.enum(['left','right','unknown']),source:ConnectedSource,confidence:z.number().min(0).max(1),timestampMs:z.number().int().positive()});
const HighwayExit=z.object({id:z.string().min(1).max(160),position:GeoPoint,ref:z.string().max(80).nullable(),name:z.string().max(200).nullable(),destination:z.string().max(300).nullable(),distanceM:z.number().min(0).max(100_000),side:z.enum(['left','right','unknown']),targetLaneIndexes:z.array(z.number().int().min(0).max(15)).max(8),source:ConnectedSource,confidence:z.number().min(0).max(1)});
const ConnectedProviderBody=z.object({providerId:z.string().min(2).max(96),timestampMs:z.number().int().positive(),spat:z.array(SpatIntersection).max(128).optional(),zones:z.array(RoadZone).max(256).optional(),weather:Weather.nullable().optional(),emergencyVehicles:z.array(EmergencyVehicle).max(128).optional(),laneTopology:LaneTopology.nullable().optional(),exits:z.array(HighwayExit).max(128).optional()});
const VehiclePositionSchema=GeoPoint.extend({speedKmh:z.number().min(0).max(350),headingDeg:z.number().min(0).max(360),accuracyM:z.number().min(0).max(10_000),timestampMs:z.number().int().positive(),source:z.enum(['gnss','device-gps','simulator'])});
const ConnectedContextBody=z.object({vehicle:VehiclePositionSchema,route:NavigationRouteSchema.nullable().optional(),collisionCritical:z.boolean().default(false)});

const EDGE_TOKEN=(process.env.KINGMAST_EDGE_TOKEN??'').trim();
function equal(a:string,b:string){const left=Buffer.from(a),right=Buffer.from(b);return left.length===right.length&&timingSafeEqual(left,right);}
function authorized(request:FastifyRequest){if(!EDGE_TOKEN)return true;const candidate=request.headers['x-kingmast-edge-token'];return typeof candidate==='string'&&equal(candidate,EDGE_TOKEN);}
function requireAuth(request:FastifyRequest,reply:FastifyReply){if(authorized(request))return true;reply.code(401).send({error:'edge-auth-required'});return false;}

export const roadContextRoutes:FastifyPluginAsync=async(app)=>{
  app.get('/v4/road-context',async(request,reply)=>{const parsed=RoadQuery.safeParse(request.query);if(!parsed.success)return reply.code(400).send({error:'invalid-road-context-query'});return getRoadContext({position:{lat:parsed.data.lat,lng:parsed.data.lng},speedKmh:parsed.data.speedKmh,radiusM:parsed.data.radiusM});});
  app.get('/v4/navigation/search',async(request,reply)=>{const parsed=SearchQuery.safeParse(request.query);if(!parsed.success)return reply.code(400).send({error:'invalid-navigation-search'});try{const near=parsed.data.lat!==undefined&&parsed.data.lng!==undefined?{lat:parsed.data.lat,lng:parsed.data.lng}:undefined;return{places:await searchNavigationPlaces(parsed.data.q,near)};}catch(error){request.log.warn({error},'geocoding provider unavailable');return reply.code(503).send({error:'geocoding-provider-unavailable'});}});
  app.post('/v4/navigation/route',async(request,reply)=>{const parsed=RouteBody.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'invalid-route-request'});try{return await calculateNavigationRoute(parsed.data.origin,parsed.data.destination);}catch(error){request.log.warn({error},'navigation provider unavailable');return reply.code(503).send({error:'navigation-provider-unavailable'});}});
  app.post('/v5/navigation/alternatives',async(request,reply)=>{const parsed=AlternativesBody.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'invalid-alternatives-request'});try{return{routes:await calculateNavigationAlternatives(parsed.data.origin,parsed.data.destination,parsed.data.evProfile as EvProfile|undefined)};}catch(error){request.log.warn({error},'navigation alternatives unavailable');return reply.code(503).send({error:'navigation-alternatives-unavailable'});}});
  app.post('/v5/navigation/intelligence',async(request,reply)=>{const parsed=IntelligenceBody.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'invalid-route-intelligence-request'});return getRouteIntelligence(parsed.data.route as NavigationRoute,parsed.data.position);});
  app.get('/v5/navigation/capabilities',async()=>({routeAlternatives:true,evEnergyEstimate:true,routeSpeedZones:true,intersectionPreview:true,chargingAlongRoute:true,blindSpotUi:true,rearCrossTrafficUi:true,vehicleControl:false,policy:'Advisory only. Public map metadata may be incomplete; posted signs and driver observation remain authoritative.'}));
  app.post('/v4/perception/speed-sign',async(request,reply)=>{if(!requireAuth(request,reply))return;const parsed=SpeedSignBody.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'invalid-speed-sign-observation'});setLatestSpeedSign(parsed.data as SpeedSignObservation);return{accepted:true};});
  app.post('/v4/road-context/cameras',async(request,reply)=>{if(!requireAuth(request,reply))return;const parsed=RuntimeCameraBody.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'invalid-camera-provider-payload',details:parsed.error.flatten()});const cameras:TrafficCamera[]=parsed.data.cameras.map((camera)=>({id:camera.id,position:camera.position,kind:camera.kind,operator:camera.operator??null,ref:camera.ref??null,directionDeg:camera.directionDeg??null,speedLimitKmh:camera.speedLimitKmh??null,viewerUrl:camera.viewerUrl??null,source:'runtime-provider',publicData:camera.publicData,distanceM:0}));replaceRuntimeCameraProvider(parsed.data.providerId,cameras);return{providerId:parsed.data.providerId,updated:cameras.length};});
  app.get('/v4/road-context/providers',async()=>({cameraProviders:configuredCameraProviderCount(),routingProvider:'osrm',geocodingProvider:'configured-nominatim-compatible',publicMapProvider:'openstreetmap-overpass',policy:'Only public or explicitly authorized traffic-camera metadata/feed endpoints may be configured. KINGMAST does not bypass camera authentication.'}));

  app.post('/connected-road/provider',async(request,reply)=>{if(!requireAuth(request,reply))return;const parsed=ConnectedProviderBody.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'invalid-connected-road-provider-payload',details:parsed.error.flatten()});const snapshot=replaceConnectedRoadProvider(parsed.data as ConnectedRoadProviderSnapshot);return{providerId:snapshot.providerId,acceptedAtMs:Date.now(),spat:snapshot.spat?.length??0,zones:snapshot.zones?.length??0,emergencyVehicles:snapshot.emergencyVehicles?.length??0,exits:snapshot.exits?.length??0,weather:Boolean(snapshot.weather),laneTopology:Boolean(snapshot.laneTopology)};});
  app.post('/connected-road/context',async(request,reply)=>{const parsed=ConnectedContextBody.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'invalid-connected-road-context-request',details:parsed.error.flatten()});return getConnectedRoadContext({vehicle:parsed.data.vehicle as VehiclePosition,route:(parsed.data.route??null) as NavigationRoute|null,collisionCritical:parsed.data.collisionCritical});});
  app.get('/connected-road/capabilities',async()=>({productVersion:'0.0.6',providerCount:configuredConnectedRoadProviderCount(),v2xSpatAbstraction:true,schoolZone:true,constructionZone:true,weatherRoadContext:true,roadHazards:true,emergencyVehicleWarning:true,laneTopology:true,highwayExitGuidance:true,intelligentSuppression:true,vehicleControl:false,policy:'Warning-only. Live SPaT and emergency-vehicle state require an authorized provider. Public-map metadata is partial and not authoritative.'}));
};
