import type { ChargingStation,GeoPoint,JunctionPreview,NavigationRoute,RouteIntelligence,SpeedZonePreview } from '@kingmast/contracts';
import { distanceMeters } from './geo.js';
import { parseMaxspeed } from './road-context.js';

const OVERPASS_URL=process.env.OVERPASS_URL??'https://overpass-api.de/api/interpreter';
const TIMEOUT_MS=5_000;
interface OsmElement{type:string;id:number;lat?:number;lon?:number;center?:{lat:number;lon?:number;lng?:number};tags?:Record<string,string>;}
interface OsmResponse{elements?:OsmElement[];}
interface RouteMatch{distanceAlongRouteM:number;distanceFromRouteM:number;position:GeoPoint;}

function pointOf(element:OsmElement):GeoPoint|null{if(typeof element.lat==='number'&&typeof element.lon==='number')return{lat:element.lat,lng:element.lon};if(element.center&&typeof element.center.lat==='number'){const lng=typeof element.center.lng==='number'?element.center.lng:element.center.lon;if(typeof lng==='number')return{lat:element.center.lat,lng};}return null;}
function cumulative(geometry:GeoPoint[]){const values=[0];for(let index=1;index<geometry.length;index++)values[index]=(values[index-1]??0)+distanceMeters(geometry[index-1]!,geometry[index]!);return values;}
function matchRoute(point:GeoPoint,geometry:GeoPoint[],distances:number[]):RouteMatch|null{if(!geometry.length)return null;let index=0,best=Number.POSITIVE_INFINITY;geometry.forEach((candidate,candidateIndex)=>{const distance=distanceMeters(point,candidate);if(distance<best){best=distance;index=candidateIndex;}});return{distanceAlongRouteM:distances[index]??0,distanceFromRouteM:best,position:point};}
function currentProgress(position:GeoPoint,geometry:GeoPoint[],distances:number[]){return matchRoute(position,geometry,distances)?.distanceAlongRouteM??0;}
function routePrefix(geometry:GeoPoint[],maxM=30_000){if(geometry.length<2)return geometry;const distances=cumulative(geometry);const result:GeoPoint[]=[];for(let index=0;index<geometry.length;index++){result.push(geometry[index]!);if((distances[index]??0)>=maxM)break;}return result;}
function bounds(geometry:GeoPoint[]){const lats=geometry.map((point)=>point.lat),lngs=geometry.map((point)=>point.lng);const margin=.003;return{south:Math.min(...lats)-margin,west:Math.min(...lngs)-margin,north:Math.max(...lats)+margin,east:Math.max(...lngs)+margin};}
function powerKw(tags:Record<string,string>){let best:number|null=null;for(const [key,value] of Object.entries(tags)){if(!key.includes('output')&&!key.includes('power'))continue;for(const match of value.matchAll(/(\d+(?:\.\d+)?)\s*k?w/gi)){const raw=Number(match[1]);const kw=/kw/i.test(match[0])?raw:raw/1000;if(Number.isFinite(kw)&&kw>0)best=best===null?kw:Math.max(best,kw);}}return best;}
function connectors(tags:Record<string,string>){return Object.keys(tags).filter((key)=>key.startsWith('socket:')&&!key.endsWith(':output')).map((key)=>key.slice(7)).filter(Boolean).slice(0,8);}
function junctionKind(element:OsmElement):JunctionPreview['kind']{const tags=element.tags??{};if(tags.highway==='traffic_signals')return'traffic-signal';if(tags.junction==='roundabout')return'roundabout';if(tags.highway==='crossing')return'crossing';return'unknown';}

export function buildRouteIntelligence(elements:OsmElement[],route:NavigationRoute,position:GeoPoint):RouteIntelligence{const geometry=route.geometry;const distances=cumulative(geometry);const progress=currentProgress(position,geometry,distances);const speedZones:SpeedZonePreview[]=[];const junctions:JunctionPreview[]=[];const chargingStations:ChargingStation[]=[];
  for(const element of elements){const point=pointOf(element);if(!point)continue;const match=matchRoute(point,geometry,distances);if(!match)continue;const ahead=match.distanceAlongRouteM-progress;const tags=element.tags??{};
    const limit=parseMaxspeed(tags.maxspeed);if(limit!==null&&match.distanceFromRouteM<=150&&ahead>=-120&&ahead<=15_000)speedZones.push({id:`speed-${element.type}-${element.id}`,position:point,distanceAlongRouteM:match.distanceAlongRouteM,limitKmh:limit,roadName:tags.name??null,source:'map',confidence:.68});
    if((tags.highway==='traffic_signals'||tags.highway==='crossing'||tags.junction==='roundabout')&&match.distanceFromRouteM<=120&&ahead>=-80&&ahead<=6_000)junctions.push({id:`junction-${element.type}-${element.id}`,position:point,distanceAlongRouteM:match.distanceAlongRouteM,kind:junctionKind(element),roadName:tags.name??null});
    if(tags.amenity==='charging_station'&&match.distanceFromRouteM<=2_500&&ahead>=-500&&ahead<=50_000)chargingStations.push({id:`charge-${element.type}-${element.id}`,name:tags.name??tags.operator??'EV charging',position:point,operator:tags.operator??null,powerKw:powerKw(tags),connectors:connectors(tags),distanceAlongRouteM:match.distanceAlongRouteM,detourDistanceM:match.distanceFromRouteM,source:'osm'});
  }
  speedZones.sort((a,b)=>a.distanceAlongRouteM-b.distanceAlongRouteM);const dedupedSpeed=speedZones.filter((zone,index,array)=>index===0||zone.limitKmh!==array[index-1]!.limitKmh||Math.abs(zone.distanceAlongRouteM-array[index-1]!.distanceAlongRouteM)>350).slice(0,24);junctions.sort((a,b)=>a.distanceAlongRouteM-b.distanceAlongRouteM);chargingStations.sort((a,b)=>a.distanceAlongRouteM-b.distanceAlongRouteM||a.detourDistanceM-b.detourDistanceM);
  return{speedZones:dedupedSpeed,junctions:junctions.slice(0,24),chargingStations:chargingStations.slice(0,24),coverage:'partial-public-map',generatedAtMs:Date.now(),notes:['Route intelligence is advisory and derived from public map metadata; posted signs and road conditions remain authoritative.','Charging availability is not live unless an authorized provider is added.']};}

async function fetchElements(route:NavigationRoute){const scoped=routePrefix(route.geometry);if(scoped.length<2)return[];const box=bounds(scoped);const query=`[out:json][timeout:10];(way(${box.south},${box.west},${box.north},${box.east})[highway][maxspeed];node(${box.south},${box.west},${box.north},${box.east})[highway=traffic_signals];node(${box.south},${box.west},${box.north},${box.east})[highway=crossing];way(${box.south},${box.west},${box.north},${box.east})[junction=roundabout];node(${box.south},${box.west},${box.north},${box.east})[amenity=charging_station];way(${box.south},${box.west},${box.north},${box.east})[amenity=charging_station];);out center tags;`;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),TIMEOUT_MS);try{const response=await fetch(OVERPASS_URL,{method:'POST',signal:controller.signal,headers:{'content-type':'application/x-www-form-urlencoded','user-agent':'KINGMAST-route-intelligence/2.5'},body:`data=${encodeURIComponent(query)}`});if(!response.ok)throw new Error(`overpass-http-${response.status}`);const raw=await response.json() as OsmResponse;return raw.elements??[];}finally{clearTimeout(timer);}}

export async function getRouteIntelligence(route:NavigationRoute,position:GeoPoint):Promise<RouteIntelligence>{try{return buildRouteIntelligence(await fetchElements(route),route,position);}catch{return{speedZones:[],junctions:[],chargingStations:[],coverage:'unavailable',generatedAtMs:Date.now(),notes:['Route intelligence provider is unavailable. Verify posted signs and use known charging infrastructure.']};}}
