'use client';

import { AlertTriangle,Bell,Camera,CarFront,ChevronRight,CircleParking,Cpu,Gauge,LocateFixed,Map,Navigation,Radio,Route,Satellite,Settings,ShieldCheck,Wifi,WifiOff } from 'lucide-react';
import { useEffect,useMemo,useRef,useState } from 'react';
import type { DetectedObject,SensorState,Severity,VehiclePosition } from '@kingmast/contracts';
import GpsSafetyMap,{ObjectGlyph} from '../components/GpsSafetyMap';
import { MOTION,useAnimatedNumber } from '../lib/motion';
import { useRealtimeTelemetry } from '../lib/realtime';
import { createSimulationFrame,withDevicePosition } from '../lib/telemetry';
import { useRoadContext } from '../lib/road-context';
import { activeManeuver,cameraLabel,driverSeverity,formatDriverDistance,routeAwareCameras,routeRemaining,speedLimitLabel } from '../lib/driver-context';

type ViewKey='drive'|'navigate'|'alerts'|'trip'|'objects'|'vehicle';
type GpsState='simulator'|'requesting'|'device'|'denied';
const primaryViews:Array<{key:ViewKey;label:string;icon:typeof CarFront}>=[{key:'drive',label:'Drive',icon:CarFront},{key:'navigate',label:'Navigate',icon:Map},{key:'alerts',label:'Alerts',icon:Bell}];
const parkedViews:Array<{key:ViewKey;label:string;icon:typeof CarFront}>=[{key:'trip',label:'Trip',icon:Route},{key:'objects',label:'Objects',icon:Radio},{key:'vehicle',label:'Vehicle',icon:Gauge}];
const severityRank:Record<Severity,number>={safe:1,caution:2,critical:3};
function statusCopy(severity:Severity){if(severity==='critical')return{title:'Slow down',subtitle:'Immediate hazard in the safety zone.'};if(severity==='caution')return{title:'Increase awareness',subtitle:'A nearby condition needs attention.'};return{title:'Clear ahead',subtitle:'Road monitoring is active.'};}
function nearestFrontObject(objects:DetectedObject[]){return objects.filter((object)=>['front','front-left','front-right'].includes(object.zone)).sort((a,b)=>a.distanceM-b.distanceM)[0]??null;}
function Metric({label,value,unit}:{label:string;value:string;unit?:string}){return <div className="metricTile"><small>{label}</small><strong>{value}{unit?<em>{unit}</em>:null}</strong></div>;}
function SensorStatus({label,icon:Icon,state}:{label:string;icon:typeof Radio;state:SensorState}){const text=state==='ok'?'Available':state==='degraded'?'Degraded':'Unavailable';return <div className={`sensorStatus sensor-${state}`}><span className="sensorGlyph"><Icon strokeWidth={1.8}/></span><span><strong>{label}</strong><small>{text}</small></span><i aria-hidden="true"/></div>;}

export default function Page(){
  const[view,setView]=useState<ViewKey>('drive');const[sequence,setSequence]=useState(0);const[gpsState,setGpsState]=useState<GpsState>('simulator');const[devicePosition,setDevicePosition]=useState<VehiclePosition|null>(null);const[limitNotice,setLimitNotice]=useState<string|null>(null);const gpsWatchId=useRef<number|null>(null);const lastLimit=useRef<number|null>(null);const live=useRealtimeTelemetry(true);
  useEffect(()=>{const timer=window.setInterval(()=>setSequence((n)=>n+1),2800);return()=>window.clearInterval(timer);},[]);
  useEffect(()=>()=>{if(gpsWatchId.current!==null&&navigator.geolocation)navigator.geolocation.clearWatch(gpsWatchId.current);},[]);
  const simulated=useMemo(()=>createSimulationFrame(sequence),[sequence]);const baseFrame=live.frame??simulated;const frame=useMemo(()=>devicePosition?withDevicePosition(baseFrame,devicePosition):baseFrame,[baseFrame,devicePosition]);const road=useRoadContext(frame.vehicle,1800);
  const alerts=useMemo(()=>[...frame.alerts].sort((a,b)=>severityRank[b.severity]-severityRank[a.severity]),[frame.alerts]);const primaryAlert=alerts[0]??null;const baseSeverity:Severity=primaryAlert?.severity??'safe';const severity=driverSeverity(baseSeverity,road.context);const frontObject=nearestFrontObject(frame.objects);const closingMps=frontObject?Math.max(0,-frontObject.relativeSpeedMps):0;const ttcTarget=frontObject&&closingMps>.1?frontObject.distanceM/closingMps:9.9;const speed=useAnimatedNumber(frame.vehicle.speedKmh,MOTION.ms.emphasized);const gap=useAnimatedNumber(frontObject?.distanceM??50,MOTION.ms.emphasized);const ttc=useAnimatedNumber(Math.min(9.9,ttcTarget),MOTION.ms.standard);
  const speedContext=speedLimitLabel(road.context);const routeCameras=useMemo(()=>routeAwareCameras(frame.vehicle,road.route,road.context?.cameras??[]),[frame.vehicle,road.route,road.context?.cameras]);const cameraAhead=routeCameras[0]??null;const maneuver=activeManeuver(frame.vehicle,road.route);const remaining=routeRemaining(frame.vehicle,road.route);const priorityObject=frontObject??[...frame.objects].sort((a,b)=>a.distanceM-b.distanceM)[0]??null;const canUseParkedTools=frame.vehicle.source==='simulator'||frame.vehicle.speedKmh<5;
  useEffect(()=>{const next=speedContext.limit;if(next===null)return;if(lastLimit.current!==null&&lastLimit.current!==next){setLimitNotice(`Speed limit is now ${next} km/h`);const timer=window.setTimeout(()=>setLimitNotice(null),5500);lastLimit.current=next;return()=>window.clearTimeout(timer);}lastLimit.current=next;},[speedContext.limit]);
  const baseStatus=statusCopy(baseSeverity);const statusTitle=baseSeverity==='critical'?baseStatus.title:speedContext.over?'Reduce speed':baseStatus.title;const statusMessage=baseSeverity==='critical'?(primaryAlert?.message??baseStatus.subtitle):speedContext.over&&speedContext.limit?`Posted limit ${speedContext.limit} km/h.`:(primaryAlert?.message??baseStatus.subtitle);
  const sensors:Array<{label:string;icon:typeof Radio;state:SensorState}>=[{label:'Front radar',icon:Radio,state:frame.sensors.radarFront},{label:'Rear radar',icon:Radio,state:frame.sensors.radarRear},{label:'Camera',icon:Camera,state:frame.sensors.camera},{label:'Vehicle CAN',icon:Wifi,state:frame.sensors.can},{label:'GNSS / IMU',icon:Satellite,state:frame.sensors.gnssImu},{label:'Safety ECU',icon:Cpu,state:frame.sensors.ecu}];

  function useDeviceGps(){if(!navigator.geolocation){setGpsState('denied');return;}if(gpsWatchId.current!==null)navigator.geolocation.clearWatch(gpsWatchId.current);setGpsState('requesting');gpsWatchId.current=navigator.geolocation.watchPosition((position)=>{setDevicePosition({lat:position.coords.latitude,lng:position.coords.longitude,speedKmh:position.coords.speed!==null?Math.max(0,position.coords.speed*3.6):baseFrame.vehicle.speedKmh,headingDeg:position.coords.heading??baseFrame.vehicle.headingDeg,accuracyM:position.coords.accuracy,timestampMs:position.timestamp,source:'device-gps'});setGpsState('device');},()=>{setGpsState('denied');setDevicePosition(null);},{enableHighAccuracy:true,maximumAge:1000,timeout:12000});}
  function useSimulator(){if(gpsWatchId.current!==null&&navigator.geolocation)navigator.geolocation.clearWatch(gpsWatchId.current);gpsWatchId.current=null;setDevicePosition(null);setGpsState('simulator');}
  function openView(key:ViewKey,parkedOnly=false){if(parkedOnly&&!canUseParkedTools)return;setView(key);}
  const edgeReady=live.state==='live';const timeLabel=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});

  return <main className={`appShell hmiV3 severity-${severity}`}>
    <aside className="sidebar" aria-label="KINGMAST navigation"><div className="appBrand"><span className="brandMark"><CarFront strokeWidth={1.9}/></span><span><strong>KINGMAST</strong><small>Driver safety</small></span></div><nav className="navList primaryNav">{primaryViews.map(({key,label,icon:Icon})=><button type="button" key={key} className={view===key?'navItem selected':'navItem'} onClick={()=>openView(key)} aria-current={view===key?'page':undefined}><Icon strokeWidth={1.8}/><span>{label}</span>{key==='alerts'&&alerts.length>0?<b>{alerts.length}</b>:null}</button>)}</nav><div className="parkedNavLabel"><CircleParking strokeWidth={1.7}/> Parked</div><nav className="navList parkedNav">{parkedViews.map(({key,label,icon:Icon})=><button type="button" key={key} className={`${view===key?'navItem selected':'navItem'} ${!canUseParkedTools?'navDisabled':''}`} onClick={()=>openView(key,true)} aria-disabled={!canUseParkedTools}><Icon strokeWidth={1.8}/><span>{label}</span></button>)}</nav><div className="sidebarFooter"><div className="parkedState"><ShieldCheck strokeWidth={1.8}/><span>Warning-only · driver remains responsible</span></div></div></aside>
    <section className="workspace">
      <header className="topbar hmiTopbar"><div><span className="eyebrow">KINGMAST SAFETY</span><h1>{[...primaryViews,...parkedViews].find((item)=>item.key===view)?.label}</h1></div><div className="topbarStatus"><span className="clockLabel">{timeLabel}</span><span className={`systemReady ${edgeReady?'':'systemDegraded'}`}>{edgeReady?<Wifi strokeWidth={1.8}/>:<WifiOff strokeWidth={1.8}/>} {edgeReady?'Sensors ready':frame.vehicle.source==='simulator'?'Demo mode':'Sensors limited'}</span>{(view==='navigate'||view==='vehicle')&&canUseParkedTools?<button type="button" className={`gpsControl gps-${gpsState}`} onClick={gpsState==='device'?useSimulator:useDeviceGps}><LocateFixed strokeWidth={1.8}/>{gpsState==='requesting'?'Locating…':gpsState==='device'?'GPS on':gpsState==='denied'?'GPS unavailable':'Use device GPS'}</button>:null}</div></header>

      {view==='drive'?<div className="cockpitLayout viewEnter"><section className="cockpitMain surface">
        <div className={`maneuverBanner ${road.route?'routeActive':'routeIdle'}`}><span className="maneuverIcon">{road.route?<Navigation strokeWidth={2}/>:<Route strokeWidth={2}/>}</span><span className="maneuverCopy">{maneuver?<><small>{formatDriverDistance(maneuver.distanceM)}</small><strong>{maneuver.step.instruction}</strong><em>{maneuver.step.roadName??'Follow route'}</em></>:road.route?<><small>Route active</small><strong>Continue on route</strong><em>{remaining!==null?`${formatDriverDistance(remaining)} remaining`:'Navigation active'}</em></>:<><small>Navigation</small><strong>Ready to navigate</strong><em>Set a destination before driving</em></>}</span><button type="button" onClick={()=>setView('navigate')}>{road.route?'Route':'Navigate'} <ChevronRight strokeWidth={2}/></button></div>
        {limitNotice?<div className="limitNotice"><Gauge strokeWidth={1.9}/>{limitNotice}</div>:null}
        <div className="cockpitStage"><div className="speedReadout"><span className="speedValue">{Math.round(speed)}</span><span className="speedUnit">km/h</span><div className={`speedLimitSign ${speedContext.over?'over':''}`}><strong>{speedContext.limit??'—'}</strong></div><small className="roadName">{speedContext.roadName??'Speed limit not verified'}</small></div>
          <div className="roadScene cockpitRoad"><div className="roadPerspective"/><div className="lane leftLane"/><div className="lane rightLane"/>{frontObject?<div className={`leadVehicle severity-${frontObject.severity}`} style={{top:`${Math.max(12,Math.min(36,41-frontObject.distanceM*.65))}%`,transform:`translateX(-50%) scale(${Math.max(.84,Math.min(1.16,1.24-frontObject.distanceM/88))})`}}><ObjectGlyph kind={frontObject.kind}/><span>{Math.round(frontObject.distanceM)} m</span></div>:null}<div className="egoVehicle"><CarFront strokeWidth={1.7}/><i/></div>{cameraAhead?<div className="routeCameraChip"><Camera strokeWidth={1.9}/><span><strong>{cameraLabel(cameraAhead.camera)}</strong><small>{formatDriverDistance(cameraAhead.routeDistanceM)} ahead</small></span></div>:null}</div>
          <div className="cockpitMetrics"><Metric label="Front gap" value={gap.toFixed(0)} unit="m"/><Metric label="TTC" value={ttc.toFixed(1)} unit="s"/>{road.route?<Metric label="Route" value={remaining===null?'—':remaining<1000?Math.round(remaining).toString():(remaining/1000).toFixed(1)} unit={remaining!==null&&remaining>=1000?'km':'m'}/>:<Metric label="Heading" value={Math.round(frame.vehicle.headingDeg).toString()} unit="°"/>}</div></div>
        <div className={`driverAlert severity-${severity}`}>{severity==='critical'?<AlertTriangle strokeWidth={2}/>:severity==='caution'?<Gauge strokeWidth={2}/>:<ShieldCheck strokeWidth={2}/>}<span><strong>{statusTitle}</strong><small>{statusMessage}</small></span></div>
      </section><aside className="cockpitSide"><section className="miniMapCard surface"><div className="sectionTitle"><span><Navigation strokeWidth={1.9}/>{road.route?'Route':'Nearby road'}</span><button type="button" onClick={()=>setView('navigate')}>Open</button></div><GpsSafetyMap vehicle={frame.vehicle} objects={frame.objects} road={road} compact/></section><section className="driverContextCard surface"><span className="eyebrow">AHEAD</span>{cameraAhead?<div className="contextHero"><Camera strokeWidth={1.9}/><span><strong>{cameraLabel(cameraAhead.camera)}</strong><small>{formatDriverDistance(cameraAhead.routeDistanceM)} on your route</small></span></div>:priorityObject?<div className="contextHero"><ObjectGlyph kind={priorityObject.kind}/><span><strong>{priorityObject.kind}</strong><small>{priorityObject.zone.replace('-',' ')} · {priorityObject.distanceM.toFixed(0)} m</small></span></div>:<div className="contextHero"><ShieldCheck strokeWidth={1.9}/><span><strong>Road clear</strong><small>No immediate object warning</small></span></div>}</section></aside></div>:null}

      {view==='navigate'?<div className="navigationView viewEnter"><section className="surface navigationSurface"><div className="sectionTitle large"><span><Navigation strokeWidth={1.9}/> Navigation</span><b>{road.route?'Route active':'Choose destination'}</b></div><GpsSafetyMap vehicle={frame.vehicle} objects={frame.objects} road={road}/></section></div>:null}

      {view==='alerts'?<div className="viewEnter"><section className="surface alertsSurface"><div className="sectionTitle large"><span><Bell strokeWidth={1.9}/> Safety alerts</span><b>{alerts.length}</b></div><div className="driverAlertList">{alerts.length?alerts.map((alert)=><div className={`driverAlertRow severity-${alert.severity}`} key={alert.id}><span className="objectGlyph"><AlertTriangle strokeWidth={1.9}/></span><span><strong>{alert.title}</strong><small>{alert.message}</small></span><b>{alert.distanceM===null?'Road':formatDriverDistance(alert.distanceM)}</b></div>):<div className="driverAlertRow severity-safe"><span className="objectGlyph"><ShieldCheck strokeWidth={1.9}/></span><span><strong>No active alerts</strong><small>Road environment is within configured thresholds.</small></span></div>}</div></section></div>:null}

      {view==='trip'?canUseParkedTools?<div className="viewEnter"><section className="surface parkedSurface"><div className="sectionTitle large"><span><Route strokeWidth={1.9}/> Current trip</span><b>{road.route?'NAVIGATION ACTIVE':'MONITORING'}</b></div><div className="positionGrid"><Metric label="Safety score" value="92" unit="/100"/><Metric label="Detected" value={frame.objects.length.toString()} unit="objects"/><Metric label="Alerts" value={alerts.length.toString()}/><Metric label="Route" value={remaining===null?'—':formatDriverDistance(remaining)}/></div><GpsSafetyMap vehicle={frame.vehicle} objects={frame.objects} road={road} compact/></section></div>:<LockedView/>:null}
      {view==='objects'?canUseParkedTools?<div className="viewEnter"><section className="surface parkedSurface"><div className="sectionTitle large"><span><Radio strokeWidth={1.9}/> Detected objects</span><b>{frame.objects.length}</b></div><div className="nearbyList detailedList">{frame.objects.map((object)=><div className="nearbyRow" key={object.id}><span className={`objectGlyph severity-${object.severity}`}><ObjectGlyph kind={object.kind}/></span><span><strong>{object.kind}</strong><small>{object.zone.replace('-',' ')} · confidence {Math.round(object.confidence*100)}% · {object.source??'simulator'}</small></span><b>{object.distanceM.toFixed(1)} m</b></div>)}</div></section></div>:<LockedView/>:null}
      {view==='vehicle'?canUseParkedTools?<div className="viewEnter"><section className="surface parkedSurface"><div className="sectionTitle large"><span><Settings strokeWidth={1.9}/> Vehicle systems</span><b>{edgeReady?'CONNECTED':'LIMITED'}</b></div><div className="sensorGrid">{sensors.map((sensor)=><SensorStatus key={sensor.label} {...sensor}/>)}</div><div className="positionGrid diagnosticsGrid"><Metric label="Control authority" value="None"/><Metric label="CAN writes" value="Disabled"/><Metric label="GPS source" value={frame.vehicle.source}/><Metric label="Sensor stream" value={edgeReady?'Live':'Fallback'}/></div></section></div>:<LockedView/>:null}
    </section>
  </main>;
}

function LockedView(){return <div className="lockedView viewEnter"><CircleParking strokeWidth={1.9}/><h2>Available when parked</h2><p>Detailed diagnostics and history stay out of the driving interaction path.</p></div>;}
